### ISSUE TITLE
`recommonmark` is deprecated

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#1082]
https://github.com/readthedocs/recommonmark#recommonmark

We should switch to `myst`: https://github.com/executablebooks/MyST-Parser

**Comment by radiantly** [comment]
Hi, could I take this up?

**Comment by sobolevn** [comment]
Sure, @radiantly! Thanks! Please, note that Hactoberst hasn't started yet. You need to wait for several days 🙂 
Otherwise, this won't be counted by their rules.
