### ISSUE TITLE
Better documentation for `is_successful` in `Result` and `Maybe`

### ISSUE THREAD

**Issue by chaichontat** [dry-python/returns#1141]
Hi, thank you for such an amazing package!

## What's wrong
I was searching for a method to check if `Result` is successful or not. However, I was surprised to not see any mentioned in both the `Result` and `Maybe` documentations. After searching through the issues, I finally found PR #95 that indicated that I should use `is_successful` which is in `returns.pipeline`.

## How is that should be
Since this is such a fundamental check, we might want to include how to do it in the `Result` and `Maybe` documentations, especially for beginners like me.

Thank you for considering!

**Comment by sobolevn** [comment]
We should totally do that! Do you want to send a PR? 🙂

**Comment by chaichontat** [comment]
Definitely! Will be making something soon.
