### ISSUE TITLE
`__slots__ = ()` missing in many base classes?

### ISSUE THREAD

**Issue by ariebovenberg** [dry-python/returns#1144]
related: #416

It seems an empty `__slots__` is forgotten in most base classes (like `Immutable`, `Equable`, etc.), greatly reducing the advantage (i.e. memory savings) of defining `__slots__` in their subclasses (e.g. `Result`, `Maybe`). Unless I'm missing something, this is not intended. In that case I will gladly submit a PR fixing this.

# Example

```python
>>> from returns.result import Success  # Result defines __slots__
>>> a = Success(4)
>>> a.__dict__  # this should not be present, but it is inherited anyway from base classes without __slots__
{}
>>> object.__setattr__(a, 'foo', 9)  # We can technically set any attribute because there is a `__dict__`
>>> a.foo
9
>>> a.__dict__
{'foo': 9}
```

# Expected behavior of slots classes

```python
>>> class Base:
...  __slots__ = ()  # necessary!
>>> class A(Base):
...  __slots__ = ('foo', )
...
>>> a = A()
>>> a.foo = 4
>>> a.bar = 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute 'bar'
>>> a.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__dict__'
```

**Comment by sobolevn** [comment]
Yes, my bad. I forgot that I need empty `__slots__`. PRs are welcome! 👍

**Comment by ariebovenberg** [comment]
@sobolevn it seems the `is_error_handled` helper of the `pytest` plugin patches success/failure containers with an extra `_error_handled` attribute which is not used outside of tests.

My suggestion would be to add this property to `__slots__`. How do you feel about adding test-specific behavior to non-test code?

The other alternatives I can think of to avoid this extra `__slots__` field are even worse:
- In the pytest plugin, do a full patch of the classes, substituting them completely. Not sure if this would even work, it'd be hacky as hell.
- set `__slots__` to include the extra property _only_ if `pytest` module can be found. Also quite hacky.

**Comment by ariebovenberg** [comment]
🤔 One other option would be to create a separate `(<object id>, object): <is error handled>` lookup dict in the tests. That'd avoid the extra attribute but we'd have to be careful to delete entries afterwards to avoid leaking memory.

Thoughts?

**Comment by sobolevn** [comment]
> My suggestion would be to add this property to __slots__. How do you feel about adding test-specific behavior to non-test code?

Or we can create a runtime subclass of a container with this new slot 🤔 
Something like `type('_Pytest' + SomeType.__name__, (SomeType,), {'__slots__': ...})`.

> One other option would be to create a separate (<object id>, <object>): <is error handled> mapping in the test plugin

This also seems like a good idea.

**Comment by ariebovenberg** [comment]
I'll try the second approach first, as it should result in 'least surprise' for the user. 🤞 let's see if it works 👀
