### ISSUE TITLE
Sphinx build broken

### ISSUE THREAD

**Issue by ariebovenberg** [dry-python/returns#1234]
# Bug report

## What's wrong

The sphinx build fails due to issues unrelated to new PRs.

example of such a build: https://readthedocs.org/projects/returns/builds/15771948/

the offending warning is:

```WARNING: Failed guarded type import with AttributeError('__globals__')```

## How is that should be

build should succeed, documentation generated without warning

## System information

whatever readthedocs.org does

**Comment by thepabloaguilar** [comment]
@sobolevn I found the issue on `sphinx-autodoc-typehints`! My PR should fix, so let's wait for the release of it:

https://github.com/tox-dev/sphinx-autodoc-typehints/pull/211
