### ISSUE TITLE
Typing issue with chained Result

### ISSUE THREAD

**Issue by SaschaSchlemmer** [dry-python/returns#124]
Take the following two functions as an example of two (or more) functions with unique failure modes (each function may fail in their own way)

```python
def fraction(x: float ) -> Result[float, ZeroDivisionError]:
    try: return Success(1/x)
    except ZeroDivisionError as e: return Failure(e)

def log_of_arg_minus_one(x: float) -> Result[float, ValueError]:
    try: return Success(log(1-x))
    except ValueError as e: return Failure(e)
```

then a computation like `fraction(x).bind(log_of_arg_minus_one)` has potentially three different outcomes:

1. the _happy_ path where both functions return a `Success`, i.e. `fraction(x)` returns `Success(y)` where `y` is a `float` and `log_of_arg_minus_one(y)` returns `Success(z)` where `z` is also a float; example  `fraction(2).bind(log_of_arg_minus_one)`
2. the failure path of `fraction` , i.e. `Failure(ZeroDivisionError)`; example: `fraction(0).bind(log_of_arg_minus_one)`
3. the failure path of `log_of_arg_minus_one`, i.e. `Failure(ValueError)`; example: `fraction(1).bind(log_of_arg_minus_one)`

Sadly this seems not to type correctly:

```python
FailureCases = Union[ZeroDivisionError, ValueError]

z: Result[float, FailureCases] = fraction(1).bind(log_of_arg_minus_one)

# Argument 1 to "bind" of "Result" has incompatible type 
# "Callable[[float], Result[float, ValueError]]"; 
# expected "Callable[[float], Result[float, Union[ZeroDivisionError, ValueError]]]"
``` 

The following also doesn't work:

```python
z: Result[float, Exception] = fraction(1).bind(log_of_arg_minus_one)

# Argument 1 to "bind" of "Result" has incompatible type 
# "Callable[[float], Result[float, ValueError]]"; 
# expected "Callable[[float], Result[float, Exception]]"
``` 

I don't know it this is an issue with `bind` (that might be fixable with a plugin) or just that `Result[S, F]` is not properly _covariant_ with respect to `F` i.e. `Result[X, A]` is considered a subtype of `Result[X, B]` when `A` is a subtype of `B`

**Comment by sobolevn** [comment]
Thanks for reporting. I will look into this.

**Comment by SaschaSchlemmer** [comment]
I think I found the source of this issue and a fix as well. Currently the return type for `bind` (in the definition of `Result` in _result.py_) is 
```python
Result[_NewValueType ,_NewErrorType]
```
 it should be 
```python
Result[_NewValueType, Union[_ErrorType ,_NewErrorType]]
``` 
to account for the accumulation of the various failure cases.

**Comment by sobolevn** [comment]
Let's ask @astynax to review this solution. @astynax , what do you think?

**Comment by astynax** [comment]
@sobolevn, if you want to keep types sane and sound,`bind` shouldn't change the type of error (so even `Result[_NewValueType ,_NewErrorType]` is a bad signature!). But we can provide a new method, that will compose error types into the one `Union`.

**Comment by sobolevn** [comment]
Ok, so the plan is: 
- `.bind()` won't change the type signature of an error
- `.unify()` will return `Union[_ErrorType, _NewErrorType]`

Thanks for your suggestions, guys! New release will be available before the 20th of August.

**Comment by SaschaSchlemmer** [comment]
I agree with @astynax that `bind` ideally shouldn't change the return type, however the accumulation of Error types is imho both very convenient (for dealing with the result of a computation that has gone wrong part way) and is way less surprising than the current behavior. If you really want `bind` to strictly do the right thing, it should just raise an exception when chaining functions with incompatible types.

**Comment by SaschaSchlemmer** [comment]
Another issue I just found is that the type of `_Success` is `Result[_ValueType, Any]` which means that `Any` will be accumulated if bind adopts the proposed behavior; imho the type of `_Success` should be `Result[_ValueType, NoType]` where `NoType` doesn't match anything.

**Comment by sobolevn** [comment]
@SaschaSchlemmer it can be `NoReturn`, but I have not tired it yet.

**Comment by SaschaSchlemmer** [comment]
Excuse me if this is bikeshedding, but I don't think it should be `NoReturn` either, since `NoReturn` is too indicate a function that always raises an Exception (which `_Success`) doesn't do. What about 

```python
class NoType: pass
```

**Comment by sobolevn** [comment]
Seems legit. Thanks!

**Comment by SaschaSchlemmer** [comment]
Another general issue with the typing of `Result` that I originally mentioned in this issue (but that turned out be unrelated) is `covariance`. Consider:

```python
z: Result[float, Exception] = Success(1).bind(fraction).bind(log_of_arg_minus_one)
```

As it currently is (regardless of the original or the proposed behavior) this doesn't typecheck. I think it should?

**Comment by sobolevn** [comment]
Yes, I think so too. I will check either `mypy` is able to do that.

**Comment by SaschaSchlemmer** [comment]
as far as I am aware mypy handles this just fine (when you set the `TypeVars` with `covariant=True`), however you will get warnings that you cannot use covariant type variables as parameters when you use them in methods/functions other than `__new__` and `__init__`

**Comment by SaschaSchlemmer** [comment]
@sobolevn scratch the `NoType` comment for `_Success` (and `_Failure` respectively). This would break something like

```python
z: Result[float, Union[ZeroDevisionError, ValueError] = Success(1).bind(fraction).bind(log_of_arg_minus_one)
``` 
because the resulting `Union[NoType, ZeroDevisionError, ValueError]` would (given that `Result` treats its `TypeVar`s covariantly) not typecheck against the provied `Union[ZeroDevisionError, ValueError]`

**Comment by SaschaSchlemmer** [comment]
According to [the powers that be](https://gitter.im/python/typing?at=5d528bc2a4efe3718df46c0d) `NoReturn` (maybe with an alias that makes more sense in this situation) would be the correct type for the missing type in `_Success` and `_Failure` respectively.

I am unfortunately still struggling a bit with setting up the git repo on my end but what I found out is:

- `NoReturn` indeed works as return type and gets flattened by `Union` (compared to `Any` which hangs around and might cause issues down the road)
- getting `Result` to type check covariantly also works; this however causes mypy errors inside because mypy dislikes covariant types as function parameters (except in `__init__` and `__new__`) such as in the definitions of `Success` and `Failure` (why are they needed anyway instead of just exposing the classes themselves?)
- when using `_Success` and `_Failure` directly instead of `Success` and `Failure` the revealed type of something like `reveal_type(_Success(1))` is `'_Success[builtins.int*]'` which is imho fairly nice visually (compared to say  `Result[builtins.int*, <nothing>]` where the `<nothing>` is actually the string representation of `NoReturn` or the previous Result[builtins.int*, Any]). Again, why have the Aliases `Success` and `Failure` instead of just exposing (and renaming) the classes themselves?
- changing `bind` to work with chained calls is possible as suggested above and basically necessitates `Result` to behave covariantly with respect to its `TypeVar`s to be useful.
- these changes didn't cause any tests to fail for me

**Comment by sobolevn** [comment]
@SaschaSchlemmer awesome work! Thanks a lot for your time and effort. What problems with `git` setup do you have? Feel free to ask for help!

**Comment by SaschaSchlemmer** [comment]
I've actually joined the gitter chat, maybe that is a more suitable channel for my issues around the setup?

**Comment by sobolevn** [comment]
@SaschaSchlemmer sorry, I don't use gitter. You can create a new github issue with your specific problem. And I will update the `CONTRIBUTING.md` docs based on the solution.

**Comment by SaschaSchlemmer** [comment]
Sry for being silent the whole time; I was quite busy. I see from your commit that 

> _Now `bind` does not change the type of an error_

So that means that the use case of chained `bind` calls is still unresolved?

**Comment by sobolevn** [comment]
`.unify` is not implemented for now. Currently I create `Union[ErrorOne, ErrorTwo]` before.

I will consider adding `.unify` in the next release.

**Comment by SaschaSchlemmer** [comment]
I also had an [interesting discussion on the typing/gitter channel](https://gitter.im/python/typing?at=5d5d71fafa99e74f6a695053) about a _dual_ function  to `unify` (like what `rescue` is to `bind`) that can be used to selectively handle error cases. Having both `unify` and it's dual function (although not possible to express using just the type system; could maybe be done with a plugin?) would be really powerful.

**Comment by sobolevn** [comment]
@SaschaSchlemmer thanks a lot for sharing this! 👍 Are you interested in giving this a try?

**Comment by SaschaSchlemmer** [comment]
You mean the an implementation for `fix` that I mentioned in the gitter channel? I think the hard part is the plugin for getting this to typecheck.

**Comment by SaschaSchlemmer** [comment]
@sobolevn I think a better name for the type aggregating `bind` might be `chain` (instead of `unify`)

**Comment by SaschaSchlemmer** [comment]
I made some process with the plugin implementation for the proposed `fix` function. Apart from one edge case I think I got everything figured out. I have to try and setup the repo again before though. Last time running the tests gave me trouble. I remember I had to out-comment something in the config file for things to work at my end.
