### ISSUE TITLE
Is isinstance necessary to work with failure?

### ISSUE THREAD

**Issue by proofit404** [dry-python/returns#126]
![Untitled](https://user-images.githubusercontent.com/1862725/62798866-00cb1900-bae8-11e9-8891-cc6a6b7a8a41.png)

**Comment by sobolevn** [comment]
I am not sure why `Union[str, Exception]` is used. Ideally ideally it would be just `Exception` with something like this:

```python
else:
      return error_code_from_exception(api_response.failure())
```

Where `error_code_from_exception` is `Callable[[Exception], dict]`.
That's how I use it.

But, I understand that pattern-patching is a better general-purpose tool for this kind of cases.

**Comment by anatoly-scherbakov** [comment]
Thank you for posting this!

I used `Union[str, Exception]` since, at some places, I am directly returning a `Failure` with an error description to be forwarded to the user:

```python
return Failure('Required fields: zipcodes, makes.')
```

At other places, I am requesting `returns` to create a `Failure` object for me out of an unhandled exception:

```python
@safe
async def execute_api_request(request: Request) -> Response:
    # do various unsafe stuff
```

In the first case, the error is expected and formulated in a human readable way; in the latter, I am just guarding against an error not known.

That influences the status code and application behavior. Anyway, it is better than it could have been because `def format_api_response()` very clearly describes every possible format of output the user might encounter. But this is not aesthetically pleasing, and `Union[str, Exception]` does not look like a nice Value Object inspired by the domain.

Maybe `Union[RequestError, UnhandledException]` would look better? Where

```python
RequestError = NewType('RequestError', str)
UnhandledException = NewType('UnhandledException', Exception)
```

**Comment by sobolevn** [comment]
Hm, thanks a lot @anatoly-scherbakov! I will try to update the docs on how to achieve what you what. I guess this is a popular case. 👍

**Comment by sobolevn** [comment]
Related: https://github.com/dry-python/returns/issues/170

**Comment by anatoly-scherbakov** [comment]
What about this?

```python
    processing_result.map(lambda c: {
        # Processing was successful
        'status': 'ok',
        **dataclasses.asdict(c)
    }).fix(match({
        # Now it was not, but the type of error can vary
        models.ETLError: lambda err: {
            'status': 'error',
            'error_type': type(err).__name__,
            **dataclasses.asdict(err)
        },
        Exception: lambda err: {
            'status': 'error',
            'error_type': type(err).__name__,
            'message': str(err)
        },
        ...: lambda err: {
            "status": "error",
            "error_type": "unknown",
            "message": str(err)
        }
    })).unwrap()
```

I have a primitive implementation for `match()` here; but the readability of the example above is a concern.

**Comment by sobolevn** [comment]
I have tried to reimplement pattern matching in python several types. The sad thing about it is that I cannot type it properly. 

Is your implementation typed? If so, I would be happy to review it and even possibly create a new project out of it. If it is not typed, then it can surely be used, but we won't recommend it officially.

I personally find this syntax ok.

**Comment by sobolevn** [comment]
@anatoly-scherbakov that's how you can now use `returns` + `classes`:

```python
from classes import typeclass
from returns.result import Result

@typeclass
def result(instance) -> str:
    """Just a typeclass definition."""


@result.instance(Result.success_type)
def _result_success(instance: Result) -> str:
     return 'success!'

@result.instance(Result.failure_type)
def _result_success(instance: Result) -> str:
     return 'error :('

some_value: Result[int, Exception]
result(some_value)  # => 'success!' or 'error :('
```

**Comment by anatoly-scherbakov** [comment]
@sobolevn Thanks! Looking into it. I assume, though, that `from typeclasses import typeclass` was meant?

**Comment by sobolevn** [comment]
We call it just `classes`: https://github.com/dry-python/classes 🙂

**Comment by anatoly-scherbakov** [comment]
Got it; I thought you meant https://github.com/thejohnfreeman/python-typeclasses/ which have similar API (but require creating a TypeVar which is more verbose). Thanks for the hint.

**Comment by sobolevn** [comment]
Please, take a look at https://github.com/dry-python/classes/issues/8
I need other people's opinions on the design.
