### ISSUE TITLE
ERROR: Could not find a version that matches returns<1.0,>=0.9.0

### ISSUE THREAD

**Issue by drconopoima** [dry-python/returns#129]
I have been using returns up until today. But when I try to install today it raises error:

ERROR: Could not find a version that satisfies the requirement returns (from versions: none)
ERROR: No matching distribution found for returns

**Comment by sobolevn** [comment]
Sorry, I am not sure what happened to you. The release is there and is untouched: https://pypi.org/project/returns/

My installation works:
```
» pip install 'returns<1.0,>=0.9.0'
Collecting returns<1.0,>=0.9.0
  Downloading https://files.pythonhosted.org/packages/1e/61/1f1c9d3391c9a236b648fdd58e1c0831f74fb97a48e7f4e8d83f0dfebfe1/returns-0.9.0-py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 437kB/s 
Requirement already satisfied: typing-extensions<4.0,>=3.7 in ./.venv/lib/python3.7/site-packages (from returns<1.0,>=0.9.0) (3.7.4)
Installing collected packages: returns
Successfully installed returns-0.9.0
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Probably some PyPI or internet issue. I am going to close this issue for now, please, feel free to reopen if it is specific to our project.

**Comment by drconopoima** [comment]
It appears that it fails to find the package when trying to install for python version 3.5, but in order to be able to troubleshoot this error I had to download the distributable wheel and try to install from it.

pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: returns requires Python '>=3.6,<4.0' but the running Python is 3.5.7

Could you please consider noting in the readme.md the minimum dependency for version 3.6? I wasn't aware that poetry handled the python version as well.

**Comment by sobolevn** [comment]
Yes, python3.5 is not supported. We support >=3.6

We already have this badge:
<img width="147" alt="Снимок экрана 2019-08-12 в 12 43 30" src="https://user-images.githubusercontent.com/4660275/62856907-d2735680-bcfe-11e9-9528-83182b4fa0ee.png">

If you think that it is not good enough - then PRs are welcome! 🙂
