### ISSUE TITLE
Refactor poetry installation in test.yml

### ISSUE THREAD

**Issue by swimmwatch** [dry-python/returns#1329]
Hello! I suggest replacing manual Poetry installation to [python-poetry-action](https://github.com/marketplace/actions/python-poetry-action).
Benefits from this approach:
1. We can commit Poetry version.
2. More simple installation.

**Comment by sobolevn** [comment]
Hi, thanks for the suggestion!

1. We can still do that with `POETRY_VERSION` env var, but we are not interested in this. We always need the latest version
2. It is simple enough in my point of view. Moreover, it is the same everywhere in my projects: https://github.com/wemake-services/wemake-python-package

So, let's keep it as is!
