### ISSUE TITLE
Make `Success` and `Failure` proper types/classes

### ISSUE THREAD

**Issue by SaschaSchlemmer** [dry-python/returns#140]
Currently `Success` and `Failure` are functions that construct instances of `_Success` and `_Failure` respectively. This has a couple of disadvantages:

- they cannot be used together with `isinstance` e.g. `isinstance(Success(1), Success)` which I think would be preferable to using helper functions like`is_successful`
- As mentioned in [issue 124](https://github.com/dry-python/returns/issues/124#issuecomment-520819578) the `reveal_type` of `Success(1)` is `Result[int, NoReturn]` instead of just `Success(int)` which looks much nicer I think
- since they are not proper types/classes they cannot be used to _constrain_ arguments in function definitions e.g.

    ```python
    def get_user_name_from_db(db: Success[db_handle], user: ID) -> Result[str, None]:
        # either return a string or None if no user found
   ```
    in this implementation, by requiring the argument `db` to be an instance of `Success[db_handle]`, one explicitly pushes the responsibility for providing a valid connection handle back to the caller`. Compare this to an implementation like:
    
    ```python
    def get_user_name_from_db(db: db_handle, user: ID) -> Result[str, None]:
        # do stuff
    ```

    which just fails at runtime when provided with a bad connection handle. [This blog post offers an interesting view on this issue](https://www.parsonsmatt.org/2017/10/11/type_safety_back_and_forth.html)

Any reason in particular why the `Success` and `Failure` dummy constructors are kept around?

**Comment by SaschaSchlemmer** [comment]
I read the comment in your commit and get the intention but draw the opposite conclusion from it i.e. since python (unlike Haskell) doesn't have pattern matching and one has to resort to `isinstance`, `Left` and `Right` are not mere type constructors (like in Haskell) but proper types themselves (to support `isinstance`). I strongly believe this is one of theses cases where abandoning strictness for practicality is the right call to make.

**Comment by sobolevn** [comment]
Oh, I might refactor this doc one more time. It is impossible to have a usable generic with a single type that has generic of two type. It would be a pain to use `class Success` and `class Failure`.

In case you will find a way that works - please, fill free to submit a PR. This is just a practical issue, not idealogical one.

**Comment by SaschaSchlemmer** [comment]
I probably overlooked something, but what is the concrete issue with literally renaming `_Success` and `_Failure` without changing anything else?

**Comment by sobolevn** [comment]
Because `class Success` will return `Success[T]` type, not `Result[A, B]` type. The same with `class Failure`

**Comment by SaschaSchlemmer** [comment]
But  isn't `_Success(T)` compatible with `Result[T, NoReturn]` anyway?

```python
x: Result[int, NoReturn] = _Success(int) # typechecks
```
