### ISSUE TITLE
Specify value returned by `safe` decorator on failure

### ISSUE THREAD

**Issue by michaelbukachi** [dry-python/returns#144]
Is there a way to specify to the value returned by the safe decorator on failure. E.g
```
@safe(value='')
def  do_something() ->Result[str, str]:
    # Something 
```
In the above example, for an error were to occur a blank string would be returned instead of _stringified exception_

**Comment by sobolevn** [comment]
That would be:

```python
@safe
def  do_something() -> str:
    ...

x: Result[str, str] = do_something.alt(lambda ex: str(ex))
```

Or you can write a custom decorator around `@safe`. 
Putting a default value here seems practical, but it would break typing in several places.

Moreover, someone will later want to add `handler=` parameter to get `value` based on the exception instance / type. So, I would prefer not to have this feature in the core.

Anyway, thanks a lot for the suggestion! I also thought about it and I happy that you brought this up.

**Comment by michaelbukachi** [comment]
Here is snippet of a custom decorator, in case anyone might have a similar question:
```
def vals(success = None, failure = None):
    def outer_wrapper(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            result = func(*args, **kwargs)
            if is_successful(result):
                if success:
                    return Success(success)
            else:
                if failure:
                    return Failure(failure)
            return result

        return wrapper

    return outer_wrapper
```
Usage:
```
@vals(failure = 'error')
@safe
def  do_something() -> Result[str, str]:
    ...
```
