### ISSUE TITLE
Provide real life examples using @pipeline

### ISSUE THREAD

**Issue by michaelbukachi** [dry-python/returns#147]
Can you provide examples of using the @pipeline? Like the one for @pipe in the README?

**Comment by sobolevn** [comment]
Is this one good enough? https://returns.readthedocs.io/en/latest/pages/pipeline.html#pipeline

**Comment by michaelbukachi** [comment]
Nope. Those methods have no bodies. So it's hard to figure out how exceptions are handled. Exceptions kept being thrown around until I realized I had to add the `@safe` decorator to the methods.

**Comment by sobolevn** [comment]
Ok, got it! Thanks. I will update the docs.
