### ISSUE TITLE
old mypy version

### ISSUE THREAD

**Issue by SaschaSchlemmer** [dry-python/returns#154]
It appears the mypy version used is 0.701; while the current release is 0.720 (which together with 0.710 brings a lot of bug-fixes and the new semantic analyzer).

**Comment by sobolevn** [comment]
Are you sure that old `mypy` is installed?
- https://github.com/dry-python/returns/blob/master/pyproject.toml#L50
- https://github.com/dry-python/returns/blob/master/poetry.lock#L633

How can I reproduce this issue?

**Comment by SaschaSchlemmer** [comment]
I guess this is a problem of me not being very versed in the use of poetry. Can you give me a hint what I must to do get this up to date in my local repo?

**Comment by sobolevn** [comment]
`poetry update`

**Comment by SaschaSchlemmer** [comment]
Thanks:) ..and shame on my for not thinking this through before asking

**Comment by sobolevn** [comment]
No problem! 👍 You can add this tip to the `CONTRIBUTING.md` with the link to the `poetry`'s docs!

**Comment by SaschaSchlemmer** [comment]
That I will do! I also found a way to make `isinstance` work with `Success` and `Failure` and got the plugin for the fancy `chain`/`fix` to work. I am in the progress of making pull requests for each of them
