### ISSUE TITLE
Please help installing returns with pyproject.toml

### ISSUE THREAD

**Issue by juxeii** [dry-python/returns#1609]
Hi, can someone help me with setting up returns library correctly?
In the installation section it is stated that

```
[mypy]
plugins =
  returns.contrib.mypy.returns_plugin
```

to go into` mypy.ini`. But I have a `pyproject.toml`. When I put
```

[tool.mypy]
plugins = returns.contrib.mypy.returns_plugin
```

at the end of `pyproject.toml` and run `poetry install`.
But I get this error
`Invalid TOML file /var/fpwork/reiss/projects/coredev/pyproject.toml: Unexpected character: 'r' at line 37 col 10`
This points to the line plugins = `returns.contrib.mypy.returns_plugin`

I am an absolute beginner with mypy :(
Or maybe I can start without mypy?

**Comment by RANJITHROSAN17** [comment]
try this 

plugins = "returns.contrib.mypy.returns_plugin"

i am also beginner to github. please try the above and say

**Comment by juxeii** [comment]
Thx, the error is gone with the quotes.
`Returns `itself is already in the dependencies section.
And now what? How do I see that the plugin has been installed correctly?
After running `poetry install` I just see:
```
poetry install
Installing dependencies from lock file

No dependencies to install or update
```
Does this mean the `mypy `plugin is installed? I am using VSC. Am I supposed to see something?

**Comment by RANJITHROSAN17** [comment]
The message "No dependencies to install or update" means that Poetry did not install any new dependencies because all the required dependencies are already installed. It does not necessarily mean that the mypy plugin is installed.

"thats good the error gone."

have a nice day
