### ISSUE TITLE
Feature Request: convenience method for ResultE.unwrap()

### ISSUE THREAD

**Issue by justin-yan** [dry-python/returns#1628]
A common use case I have when using ResultE is that I'd like to access the value if it's a Success, but otherwise raise the encapsulated exception if it's a Failure.  As a very simple example:

```
def res_unpack(res: ResultE):
    match res:
        case Success(v):
            return v
        case Failure(e):
            raise e
```

I was curious if it would be possible to have something like this functionality in the upstream library in some capacity.  Thanks for your consideration!

**Comment by sobolevn** [comment]
https://github.com/dry-python/returns/blob/master/returns/functions.py#L109 wont this work for you?

**Comment by justin-yan** [comment]
Hello!  Thank you for responding!

I took a look at issue #56, and I believe yes the function you describe does do what I want, e.g. https://github.com/dry-python/returns/issues/56#issuecomment-915021763.

I use this quite frequently and I think it would be helpful to have a single convenience method, but reading your rationale here (https://github.com/dry-python/returns/issues/56#issuecomment-497824046) I understand why you don't want to include this on the `Result` type itself, which is totally fair.

Thanks for taking the time to look at this!
