### ISSUE TITLE
Contradictory code vs docstring for several methods of `maybe.Nothing`

### ISSUE THREAD

**Issue by anatoly-scherbakov** [dry-python/returns#174]
Example: https://github.com/dry-python/returns/blob/master/returns/maybe.py#L146

```python

    def fix(self, function):
        """
        Applies function to the inner value.
        Applies 'function' to the contents of the 'Some' instance
        and returns a new 'Some' object containing the result.
        'function' should not accept any arguments
        and return a non-container result.
        .. code:: python
          >>> def fixable(_state) -> str:
          ...      return 'ab'
          ...
          >>> Nothing.fix(fixable) == Some('ab')
          True
        """
        return Maybe.new(function(self._inner_value))
```

The docstring suggests that

> 'function' should not accept any arguments

but in fact `self._inner_value` (which is a `Nothing` object as far as I can see) is passed instead.

Not sure what intended behavior was.

**Comment by sobolevn** [comment]
Oh, I see. That's an artifact from the old implementation where `Nothing.fix(lambda: ...)` was allowed.

Doctests are always correct, because they are checked. Can you please send a PR with the fix to the docs?
