### ISSUE TITLE
feat: add partition func for result ojbects

### ISSUE THREAD

**Issue by RomanMIzulin** [dry-python/returns#1905]
# Feature request

Given a list of results, returns a pair where the first element is a list of all the values inside `Success` and the second element is a list with all the values inside `Failure`.

stacks with https://github.com/dry-python/returns/issues/1899

reference: https://hexdocs.pm/gleam_stdlib/gleam/result.html#partition

**Comment by sobolevn** [comment]
Let's start with this one.
