### ISSUE TITLE
Add background for the logo 

### ISSUE THREAD

**Issue by orsinium** [dry-python/returns#195]
On a black background logo looks strange  

![](https://i.imgur.com/XvG8GeI.jpg)

**Comment by sobolevn** [comment]
@proofit404

**Comment by proofit404** [comment]
Hi guys,

Thank you @orsinium  for the report!

I think that should not be solved by the background color.

But instead, we should have two variants of logos. One in black. One in white. Both with the transparent background color.

I'll take care of it.

Best regards,
Artem.

**Comment by orsinium** [comment]
Which one will be in README? The screenshot above is from Github mobile client with a dark theme.

**Comment by homeworkprod** [comment]
On approach is to add a white/very light outline. It'd be close to invisible in light mode (on current GitHub at least) and makes the shape stand out in dark mode.

**Comment by sobolevn** [comment]
@homeworkprod any help is appreciated. None of us are good at drawing. 😞

**Comment by homeworkprod** [comment]
Is there a source SVG file available of the *returns* logo?

Found only a PNG in https://github.com/dry-python/brand/tree/master/logo.

**Comment by homeworkprod** [comment]
@orsinium, I was more thinking of this (just an outer outline):
![returns-white-outer-contour](https://user-images.githubusercontent.com/95277/78918729-20f51280-7a91-11ea-95c7-8f4aa2288710.png)

**Comment by sobolevn** [comment]
@homeworkprod looks great! Would you like to submit it?

**Comment by homeworkprod** [comment]
Sure: https://github.com/dry-python/brand/pull/2
