### ISSUE TITLE
Question on the algebra of the Result type

### ISSUE THREAD

**Issue by abravalheri** [dry-python/returns#196]
Hello guys, awesome package, thank you very much!

I am learning a lot just by playing with it. However, there is something I still don’t understand, and maybe you can help me.

Intuitively, I was expecting that if you bind a `Result[S1, F1]` with a function `S1 -> Result[S2, F2]`, you would get back a `Result[S2, Union[F1, F2]]`. In my mind this makes sense…, if the first result was already a failure you have a `Failure[F1]`, if the function fails, you have a `Failure[F2]`, so for me it makes sense considering the final outcome a `Failure[Union[F1, F2]]`...

So I went ahead and tried something like this:

```python
StrId = NewType("StrId", str)
ValidId = Union[int, StrId]
ResourceRef = Union[str, Dict[str, Optional[ValidId]]]
_Ids = Tuple[Optional[ValidId], ...]
_Names = Tuple[str, ...]

def _normalize_reference(
    reference: ResourceRef
) -> Result[Tuple[_Names, _Ids], Union[LookupError, ValueError]]: ...

def _create(
    names_ids: Tuple[_Names, _Ids]
) -> Result[ValidId, Union[LookupError, ValueError, StopIteration]]: ...

...

 _normalize_reference(reference).bind(_create)
```

To which, mypy said:
```
store.py:320: error: Incompatible return value type
(got "Result[Union[int, StrId], Union[LookupError, ValueError]]",
 expected "Result[Union[int, StrId], E]")
          return _normalize_reference(reference).bind(_create1)
                 ^

store.py:320: error: Argument 1 to "bind" of "Result" has incompatible type
"Callable[[Tuple[Tuple[str, ...], Tuple[Union[int, StrId, None], ...]]], Result[Union[int, StrId], Union[LookupError, ValueError, StopIteration]]]"; expected
"Callable[[Tuple[Tuple[str, ...], Tuple[Union[int, StrId, None], ...]]], Result[Union[int, StrId], Union[LookupError, ValueError]]]"

         return _normalize_reference(reference).bind(_create1)
                                                     ^
```

So obviously my assumption was wrong :P
Looking at the code, I realised that the Result class is defined in terms of a `_ErrorType = TypeVar('_ErrorType', covariant=True)`

What I am asking myself is:
1.	Is mypy complaining because `Union[LookupError, ValueError, StopIteration]` cannot be compared in a covariant way to `Union[LookupError, ValueError]`?
2.	If `_ErrorType` was defined to have a bound to `BaseException` would this change anything? Would mypy recognise both `Union[LookupError, ValueError, StopIteration]` and `Union[LookupError, ValueError]` as a subtype of `BaseException`?
3.	Or this is just a matter on how to define the type algebra in the `bind ` function, and I would have to re-write the Result, Failure and Success classes themselves to encode this new algebra in the bind signature?

Do you have any thoughts on this topic?

**Comment by sobolevn** [comment]
Hi, @abravalheri! Thanks a lot for raising this!

I guess, that `.bind` should not really do that.
We need another method `.unify()` and it will work the way you like.

This is already proposed and discussed here: https://github.com/dry-python/returns/issues/124

Thanks a lot for your interest! 👍

**Comment by abravalheri** [comment]
AAh OK, I see. Thank you very much!

**Comment by sobolevn** [comment]
Let's leave it opened for now, I have to work on `.unify()`
