### ISSUE TITLE
IO usage

### ISSUE THREAD

**Issue by galen104** [dry-python/returns#197]
I'm just doing some experiment with IO, and I can't figure out how I can make it work :/
Consider a simple example like this:

```
a = IO(4)
b = IO(7)
print(a > b)
```
it give me this:

```
TypeError: '>' not supported between instances of 'IO' and 'IO'
```
so I cannot compare IO, I cannot extract value from it, how I'm supposed to use it? What am I missing?
As an example I will give you a simple use case that I'm working on. I have a function that must check a csv file.

```
@safe
def row_count(filename: str) -> IO[int]:
    with open(filename, encoding='utf-8') as csv_file:
        return IO(sum(1 for _ in csv_file))


@safe
def no_results_inside(filename: str) -> IO[bool]:
    with open(filename, 'rb', 0) as file, \
            mmap.mmap(file.fileno(), 0, access=mmap.ACCESS_READ) as s:
        if s.find(b"No Results Found") != -1:
            return IO(True)
        else:
            return IO(False)


@safe
def is_file_empty(filename: str, empty_file: int = 4096) -> IO[bool]:
    size: int = os.path.getsize(filename)
    return IO(True) if size <= empty_file else IO(False)

@safe
@pipeline
def is_valid_csv(filename: str, log: Logger, empty_file: int = 4096, limit: int = 1000000) -> IO[bool]:
    bname = {os.path.basename(os.path.normpath(filename))}
    if is_file_empty(filename, empty_file).unwrap() == IO(True):
        log.warning(f"File {bname} is empty")
        if no_results_inside(filename).unwrap() == IO(True):
            log.warning(f"File {bname} has no valid data")
            try:
                os.remove(filename)
                log.info(f"Removing empty file: {bname}")
                return IO(False)
            except OSError as e:
                log.error(f"Error while deleting file: {bname}")
                raise e
    elif row_count(filename).unwrap() >= IO(limit):
        log.error(f"Exceed limit file {bname}")
        return IO(False)
    else:
        return IO(True)
```

ps: I'm sorry but I'm totally new to python so my code is probably just a bad one :)

**Comment by sobolevn** [comment]
You have to use `.map` or `.bind` methods for `IO` to work with it: https://returns.readthedocs.io/en/latest/pages/container.html#working-with-containers
You have also an opportunity to `unsafe_perform_io`: https://returns.readthedocs.io/en/latest/pages/io.html#unsafe-perform-io

**Comment by galen104** [comment]
With this:

```
elif row_count(filename).unwrap().map(lambda x: x >= limit) == IO(True):
```
the function works.

ps: I don't known if it was a good idea make as `IO[bool]` the result of the functions like `is_file_empty()`. Compare to `IO(True)` feels strange..

**Comment by sobolevn** [comment]
I will try to rewrite your code tomorrow, there are some improvements available 🙂 
Sorry for the delay!

**Comment by galen104** [comment]
Thanks, I really appreciate.

**Comment by galen104** [comment]
Today I was trying some toying application

```
import pickledb
import pandas as pd
from typing import List
from returns.io import IO
from returns.result import Result, Success, Failure
from toolz.curried import map, filter
from returns.pipeline import pipeline, pipe, is_successful
from returns.functions import box

keynames_file = 'key_names.csv'
success_dbfile = 'success.db'
failed_dbfile = 'failed.db'

success_db = pickledb.load(success_dbfile, False)
failed_db = pickledb.load(failed_dbfile, False)

def load_dataset_ids(file: str) -> IO[Result[List[str], Exception]]:
    try:
        # failure test1
        #return Failure(Exception("Test1"))
        dataset_ids_df = pd.read_csv(file)
        return IO(Success(dataset_ids_df['KeyFamilyId'].tolist()))
    except Exception as e:
        return IO(Failure(e))

def clean_dataset_id(ds_id: str) -> str:
    return ds_id.strip()

def db_getall(db: pickledb) -> IO[Result[List[str], Exception]]:
    try:
        # failure test2
        #return IO(Failure(Exception("Test2")))
        return IO(Success(list(db.getall())))
    except Exception as e:
        return IO(Failure(Exception(e)))

success_db.set('test1', True)
success_db.set('test2', True)


def get_success_list(x) -> bool:
    return db_getall(success_db).bind(lambda x: x).bind(lambda y: x not in y)

def get_failed_list(x) -> bool:
    return db_getall(failed_db).bind(lambda x: x).bind(lambda y: x not in y)


ret = pipe(load_dataset_ids,
           box(lambda x: x.map(filter(get_success_list))),
           lambda x: x.map(filter(get_failed_list)),
           lambda x: x.map(map(clean_dataset_id)),
           lambda x: x.map(list))(keynames_file)

print(ret)
```

This just load a list from a csv file, and filter it from values read from two pickledb file.
It not efficient, it's just a toy problem to better understand how to use this type of programming, but there are a lot of big problems!
I'm thinking too much in a procedural way?
I come from C programming (embedded world) and this is confusing for me, at least for now :\

**Comment by sobolevn** [comment]
Sorry, I didn't have the time during the week, but this is still in my backlog. I hope to get back to this tomorrow. Thanks for your interest and your patience 🙂

**Comment by galen104** [comment]
No problem and thanks for your time :)

ps: for the last example I was overthinking, I replace lists with sets

```
...
def filter_success(s: Set) -> Result[Set, Exception]:
    return db_getall(success_db).bind(lambda x: x).map(lambda y: s-y)


def filter_failed(s: Set) -> Result[Set, Exception]:
    return db_getall(failed_db).bind(lambda x: x).map(lambda y: s-y)


ret = pipe(load_dataset_ids,
           box(filter_success),
           box(filter_failed),
           lambda x: x.map(map(clean_dataset_id)),
           lambda x: x.map(list))(keynames_file)
```
Now the problem is always the same, the IO part. In my example basically only `db_getall()` return an IO and that "cost me" another `bind`. I will wait your answer.
Thanks again for your time and patience.

**Comment by sobolevn** [comment]
Hi, @galen104 
I am really sorry that it took me so long to finally find the time to help you.

## Initial post

```python
a = IO(4)
b = IO(7)
print(a > b)
```

Container do not work this way. It is intentional. You are supposed to use `.bind` and `.map`, but I see your point here. Imagine that we have several values like `IO(3)`, `IO(5)`, `IO(10)` and we are asked to get `X + Y / Z` value. Oh, it would be a mess of `.map`s and `lambda`s!

I suggest to add `IO.context` function that will work like so:

```python
x = IO(3)
y = IO(5)
z = IO(10)

IO.context(lambda x, y, z: x + y / z)(x, y, z) == IO(3.5)
# => IO(3.5) == IO(3.5)
# => True
```

I'll open a separate issue for that. Thanks a lot for the idea!

## Database example

So, let's dive into the source code you showed me: https://github.com/dry-python/returns/issues/197#issuecomment-559610506

First of all, you don't have to manually wrap values in `Success` and `IO`, we have helpers for that:

```python
from returns.result import safe
from returns.io import impure

@impure  # IO[Result[List[str], Exception]]
@safe  # Result[List[str], Exception]
def load_dataset_ids(file: str) -> List[str]:
    dataset_ids_df = pd.read_csv(file)
    return dataset_ids_df['KeyFamilyId'].tolist()

@impure  # IO[Result[List[str], Exception]]
@safe  # Result[List[str], Exception]
def db_getall(db: pickledb) -> List[str]:
    return list(db.getall())
```

Secondly, yours `filter_success` and `filter_failed` are identical.
Moreover, it is impure and unsafe. It would be hard to compose it with pure input.
We can improve that!

Also, you don't ever need `.bind(lambda x: x)` because it is basically is `.bind(identity)` that returns the object itself wrapped in the same container.

Newly `IO.context` can be really helpful here.

And then you final composition:

```python
@pipeline
def main(filename: str) -> IO[Result[Set[str], Exception]]:
    dataset = load_dataset_ids(filename)
    successful = db_getall(success_db)
    failed = db_getall(success_db)

    return IO.context(
        lambda pure_dataset, pure_success, pure_fail: (
            # Now we can work with the sets themselfs:
            pure_dataset.unwrap() - pure_success.unwrap() - pure_fail.unwrap()
        )
    )(dataset, successful, failed)
```

This example is not tested, by I hope you will get the idea.

**Comment by galen104** [comment]
I have some trouble to properly understand how to use `IO`.

```
@dataclass
class Error:
    msg: str

def read_file(filename: str) -> IO[Result[pd.DataFrame, Exception]]:
    try:
        return IO(Success(pd.read_csv(filename, encoding='utf-8', low_memory=False)))
    except Exception as ex:
        return IO(Failure(ex))


def do_stuff(df: pd.DataFrame) -> Result[pd.DataFrame, Exception]:
    try:
        # pandas stuff
        df2 = df.tail(3)
        return Success(df2)
    except Exception as ex:
        return Failure(ex)


@pipeline
def process(filename: str) -> IO[Result[pd.DataFrame, Error]]:
    return read_file(filename).map(lambda res: res.alt(lambda ex: Error(msg=f"Failed with ex: {ex}")).bind(do_stuff))
```
there is a way to simplify the code?

**Comment by sobolevn** [comment]
I guess you can just drop the `IO` in this case. Why?

`IO` is used to separate pure code from impure code in large code bases.
It is not suited for simple scripts.

But, your code can be simplified by using `@impure` and `@safe` decorators.

**Comment by sobolevn** [comment]
Now when `io_squash` is released, this can be closed. Thanks a lot for your questions!
