### ISSUE TITLE
Add `IO.context` to work with multiple `IO` values at once

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#201]
Imagine that we have several values like `IO(3)`, `IO(5)`, `IO(10)` and we are asked to get `X + Y / Z` value. Oh, it would be a mess of `.map`s and `lambda`s!

I suggest to add `IO.context` function that will work like so:

```python
x = IO(3)
y = IO(5)
z = IO(10)

IO.context(lambda x, y, z: x + y / z)(x, y, z) == IO(3.5)
# => IO(3.5) == IO(3.5)
# => True
```

Related https://github.com/dry-python/returns/issues/197

**Comment by sobolevn** [comment]
`IO.context` does not type well. Because `IO.context(lambda x, y, z: x + y / z)` does not know any real values when it is created. And `mypy` cannot tell that type vars from `IO.context(lambda x, y, z: x + y / z)` depend from `(x, y, z)`

So, I suggest to use `IO.squash` instead:

```python
x = IO(1)
y = IO('a')
z = IO.squash(x, y)

assert z == IO((1, 'a'))
reveal_type(z)
# => IO[Tuple[int, str]]
```

And you can use it like so:

```python
IO.squash(x2, y2).map(lambda value: value[0] > value[1])
# => IO[bool]
```

**Comment by sobolevn** [comment]
Can we also apply `squash` to other types: `Maybe`, `Result`? I don't know yet.
@astynax @galen104 @proofit404 would love to hear your opinion, guys.

**Comment by sobolevn** [comment]
I guess not, `Maybe.squash(Maybe.new(x), Maybe.new(y))` is not `Maybe.new((x, y))`

**Comment by galen104** [comment]
Right now I don't feel the need to apply `squash` to other types.
That said, I'll ask you a question, in a simple example like this:

```
@dataclass
class Error:
    msg: str


def read_file(filename: str) -> Result[pd.DataFrame, Exception]:
    try:
        return Success(pd.read_csv(filename, encoding='utf-8', low_memory=False))
    except Exception as ex:
        return Failure(ex)


@pipeline
def process(filename: str) -> Result[pd.DataFrame, Error]:
    df = read_file(filename).alt(lambda ex: Error(msg=f"Failed with ex: {ex}")).unwrap()
    try:
        # very long pandas stuff
        df2 = df.tail(3)
        # ....
    except Exception as ex:
        return Failure(Error(msg=f"Failed with ex: {ex}"))
    return Success(df2)
```

how can IO be added without too much "noisy stuff"?
I have some trouble working with nested containers like `IO[Result[pd.DataFrame, Exception]]` :(

```
def read_file(filename: str) -> IO[Result[pd.DataFrame, Exception]]:
    try:
        return IO(Success(pd.read_csv(filename, encoding='utf-8', low_memory=False)))
    except Exception as ex:
        return IO(Failure(ex))


def do_stuff(df: pd.DataFrame) -> Result[pd.DataFrame, Exception]:
    try:
        # pandas stuff
        df2 = df.tail(3)
        return Success(df2)
    except Exception as ex:
        return Failure(ex)

@pipeline
def process(filename: str) -> IO[Result[pd.DataFrame, Error]]:
     df = read_file(filename).map(lambda res: res.alt(lambda ex: Error(msg=f"Failed with ex: {ex}")).unwrap())
     # df is IO[pd.DataFrame], there is a better way to extract it?
    df.map(do_stuff)  # how can I now transform `Exception` to `Error`
```
with `IO` the program even if simple seems overcomplicated, on the other hands I use `Result` regularly and it simplifies my work.

NOTE: the map from `Exception` to `Error` is mandatory, not by this toy example but to me to understand how to properly works with nested containers.

PS: I don't use `@safe` and `@impure` because they broke the auto completion and other stuff (I'm using PyCharm)

Thanks
