### ISSUE TITLE
Consider adding Reader monad

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#216]
Useful pieces of information:
- https://gist.github.com/dustingetz/3172127
- https://dev.to/gcanti/getting-started-with-fp-ts-reader-1ie5
- https://github.com/dbrattli/OSlash/blob/master/tests/test_reader.py
- https://github.com/dbrattli/OSlash/wiki/Three-Useful-Monads#the-reader-monad

It might be used for type-safe DI and context-based computations.
It might be a good addition.

**Comment by sobolevn** [comment]
https://softwaremill.com/reader-monad-constructor-dependency-injection-friend-or-foe/

**Comment by pvldruzhinin** [comment]
I'd like to work on this issue

**Comment by sobolevn** [comment]
Sure! Feel free to ask any questions you have.

**Comment by sobolevn** [comment]
http://learnyouahaskell.com/for-a-few-monads-more
