### ISSUE TITLE
Consider adding `equals` function

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#250]
It should work like this:

```
x: Result[int, str] = Success(1)
assert equals(x, 1) == True

y: Result[int, str] = Failure('a')
assert equals(y, 'a') == False
```

**Comment by thepabloaguilar** [comment]
I'll take this issue, if possible!

**Comment by sobolevn** [comment]
Well, actually I don't think it is a good idea anymore. 

First of all, it is easy to compare values with other values. Like `Success(1) == Success(1)` or `Success(1) == Failure('a')`
But, this is not easy. And it will require lots of typing and good portion of magic.

I would love to close this one as well. Less is more 🙂

**Comment by sobolevn** [comment]
@thepabloaguilar there's one for you: we need pointfree helpers! Lots of them, actually. I will create new issues shortly.

**Comment by sobolevn** [comment]
P.S. Thanks a lot for you help. I really appreciate it.

**Comment by thepabloaguilar** [comment]
> @thepabloaguilar there's one for you: we need pointfree helpers! Lots of them, actually. I will create new issues shortly.

Ok, I'm waiting for those.

**Comment by thepabloaguilar** [comment]
> P.S. Thanks a lot for you help. I really appreciate it.

You're welcome man, I really like to contribute with this lib 'cause I'm starting with the functional world and I learned a lot with every functionality and your articles references in the documentation!

**Comment by sobolevn** [comment]
Done! #376
