### ISSUE TITLE
Create `collect`, `collect_success`, and `collect_failure` functions

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#255]
It should work like so:

- `collect(List[IO[a]]) -> IO[List[a]]`
- `collect_success(List[Result[a, b]]) -> Result[List[a], b]`
- `collect_failure(List[IOResult[a, b]]) -> IOResult[a, List[b]]`

**Comment by sobolevn** [comment]
Turns out it is not so easy

**Comment by tewe** [comment]
According to Hoogle, Haskell doesn't have those either.

**Comment by sobolevn** [comment]
1. https://sanctuary.js.org/#lefts
2. https://sanctuary.js.org/#rights
