### ISSUE TITLE
isRight/isLeft - like functions?

### ISSUE THREAD

**Issue by lainiwa** [dry-python/returns#259]
I was playing around with Returns and I found myself in situation where I feel it would make sense to check the result without actually unwrapping it.

Might it maybe be a good idea to have this functions in Returns (question probably applies to [`isNothing`/`isJust`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Maybe.html) as well)?

**I considered:**

* using `isinstance(result, returns.result._Success)` or something, but the documentation explicitly discourages use of the "internal" types
* doing things like `result.value_or(None) is not None`, but this becomes no better than just using `None`s

**Comment by sobolevn** [comment]
We have `is_successful` function: https://returns.readthedocs.io/en/latest/pages/pipeline.html#is-successful

Does it solve your problem?

**Comment by lainiwa** [comment]
Yes, thank you!

**Comment by sobolevn** [comment]
Happy to help!
