### ISSUE TITLE
Two Railways with flow and safe

### ISSUE THREAD

**Issue by SomeUser55** [dry-python/returns#262]
Consider stepwise transformations on bunch of data frames. I put them in flow. 
Some data frame can be absent or invalid. So I wrap steps with safe decorator. Should I inside step check the Result from previous step whether it is Success or Failure? 
If not - what is the true way to implement ROP with returns?

**Comment by sobolevn** [comment]
Can you please provide a code example?

**Comment by SomeUser55** [comment]
Honestly speaking, I cannot show code due to NDA. I catch the idea of ROP, but lack for detailed examples of returns usage in big projects.

**Comment by sobolevn** [comment]
So, let's make this example anonymous. I would love to contribute to the docs if I can.

**Comment by sobolevn** [comment]
I would love to help, but cannot do that without code samples 🙂
