### ISSUE TITLE
Function to replace safe decorator

### ISSUE THREAD

**Issue by tewe** [dry-python/returns#263]
Decorators work well with mypy, thanks to the plugin. They do not work with the type checker built into the PyCharm IDE.

This makes me reluctant to use them, as auto-completion is a big motivation for using type hints in the first place.

But especially `@safe` saves a lot of typing, so a replacement would be nice. It should be possible as a function, like `Try` in Scala.

**Comment by sobolevn** [comment]
Can you please provide a code sample of `Try` in `python`?
I will report this issue to PyCharm team.

**Comment by sobolevn** [comment]
I am going to close this one for now. Because

- `safe` can be used as a function: `x = safe(input)`
- `safe` cannot be modeled as `Try`, because python is statement based, not expression based

If you have any other feedback, feel free to reopen! 👍
