### ISSUE TITLE
Variant of safe that preserves the argument that lead to an exception

### ISSUE THREAD

**Issue by stereobutter** [dry-python/returns#264]
I propose a function/decorator (maybe `attempt` would be a good name?) similar to `safe` with the twist of returning `Failure(bad_input)` from `safe(f)(bad_input)` instead of `Failure(SomeException)`. An example where this would be useful:

```python
(
    attempt(json.loads)('<hello world>')
    .alt(lambda s: ValueError(f'"{s}" is not a valid json')) 
)
# Failure(ValueError('"<hello world>" is not a valid json'))
```

**Comment by sobolevn** [comment]
Oh, I see. Do you want to send a PR?

**Comment by SaschaSchlemmer** [comment]
I haven't worked with mypy plugins/decorators in a while so I'm not sure if there is a neat way to implement `attempt` (in a typesafe way) leveraging the existing implementation of `safe`? Of course one could just copy past the implementation for `safe` and its plugin but that is imho not a very nice solution. What do you think?

**Comment by sobolevn** [comment]
It can be a good be a start.

**Comment by SaschaSchlemmer** [comment]
After looking into this for the last half hour I think getting this to typecheck without something like [https://www.python.org/dev/peps/pep-0612/](https://www.python.org/dev/peps/pep-0612/) will require  its own plugin since one has to get at the types of the arguments of `f` in `attempt(f)`. :(

**Comment by sobolevn** [comment]
I think so too, that's the big problem with `mypy`.

**Comment by thepabloaguilar** [comment]
I was thinking about the implementation here, one thing we need to define is what to do with functions that has multiple parameters, like, if my function has 3 arguments like:

```python
def my_func(a, b, *, c):
    pass

my_func(1, 2, c=3)
```

What should be inside the Result? A tuple where the first element is the positional args and then the second the keyword args?

**Comment by thepabloaguilar** [comment]
Any thoughts @sobolevn??

**Comment by sobolevn** [comment]
I think that functions with multiple arguments should not be allowed in this case.
