### ISSUE TITLE
Add `NoDeps` type alias for `Any`

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#273]
Sometimes `RequiresContext` and other similar types might be used with no explicit dependencies (due to some existing API requirements for example).

So, we need to have `NoDeps` type alias for `Any`.

**Comment by thepabloaguilar** [comment]
I took a look at `RequiresContext`, I made a few changes:

```python
# imports

_NoDeps = Any

class RequireContext:
    # code
    empty: ClassVar[_NoDeps] = object()
    #code
```

Is it something like that?

**Comment by sobolevn** [comment]
Yes, looks like it. But it should be public. And reexported in `context/__init__.py`

**Comment by thepabloaguilar** [comment]
Could I take this one?

**Comment by sobolevn** [comment]
Thanks a lot!
