### ISSUE TITLE
Add Future[A] that helps with async code

### ISSUE THREAD

**Issue by SaschaSchlemmer** [dry-python/returns#274]
I am lately writing a lot of asynchronous code (using _asyncio_ mostly) and while `async`/`await` is fairly straight forward and nice to work with, it hinders writing modular code with small functions and reuse of said functions. This is imho due to two issues in particular:

1. regular functions `def foo(...` and coroutines `async def bar(...` have different calling semantics. For a regular function you just do `foo(...)` to get your result back while for coroutines you need to await the result, i.e. use `await bar(...)`
2. coroutines don't compose well (without pouring `await` all over your code)

Let's define a couple simple functions (both regular and coroutines) to illustrate these issues:

```python
def double(x): 
    return 2*x

async def delay(x):
    return x

async def double_async(x):
    return 2*x
```

Cases:

1. Composing regular functions just for reference - easy: 
   ```python
   double(double(1))
   ```

2. Composing regular and coroutine functions V1 - not so bad,:
    ```python
    await double_async(double(1))
    ```

3. Composing regular and coroutine functions V2 - awkward with the await thrown into the middle:
    ```python
    double(await double_async(1))
    ```

4. Composing two coroutine functions  - `await`s galore :
    ```python
    await double_async(await double_async(1))
    ```

To ease this pain I propose a (monad-like) container that implements `map` and `bind` so that functions can be chained nicely 

```python
class Promise:
    
    def __init__(self, coro):
        self._coro = coro
        
    def map(self, f):
        async def coro():
            x = await self._coro
            return f(x)
        return Promise(coro())
    
    def bind(self, f):
        async def coro():
            x = await self._coro
            return await f(x)
        return Promise(coro())
    
    def __await__(self):
        return self._coro.__await__()
```

### Usage 

- Wrap a coroutine (function defined with `async def`) to create an instance of `Promise`. 
    ```python
    p = Promise(delay(1))
    await p  # get the result of the wrapped coroutine
    ```
- Call a regular function on an instance of `Promise`
    ```python
    await Promise(delay(1)).map(double)
    ```
- Call a coroutine on an instance of `Promise`
    ```python
    await Promise(delay(1)).bind(double_async)
    ```

### Extended example
Since the examples above don't look too intimidating, behold:

```python
await (
    double_async(
        double(
            await double_async(
                await delay(1)
            )
        )
    )
)
```
vs.:

```python
await (
    Promise(delay(1))
    .bind(double_async)
    .map(double)
    .bind(double_async)
)
```
Feedback greatly appreciated!

**Comment by SaschaSchlemmer** [comment]
A perhaps more interesting example:

```python
await (
    Promise(delay([1,2,3]))
    .map(partial(map, double))   # double each entry
    .map(partial(map, double_async))   # double each entry with a coroutine
    .bind(star_gather)  # gather the result with a coroutine
)
# ==> [4, 8, 12]
```
where `star_gather` is simply 

```python
async def star_gather(list_of_coros):
    return await asyncio.gather(*list_of_coros)
```

**Comment by sobolevn** [comment]
Hi, @SaschaSchlemmer! Thanks a lot! 

This is indeed in our list: #235 I will close that issue and keep this one to discuss this topic.

The problem with `asyncio` is that I don't use it at all. And I am not sure how to design an API for it. I would be happy if you can help me with that. 

P.S. Considering `partial`, see #267

**Comment by sobolevn** [comment]
Inspirations:

- https://zio.dev/docs/overview/overview_basic_concurrency

And:

- https://github.com/gcanti/fp-ts/blob/master/docs/modules/Task.ts.md
- https://github.com/gcanti/fp-ts/blob/master/docs/modules/TaskEither.ts.md
- https://github.com/gcanti/fp-ts/blob/master/docs/modules/ReaderTask.ts.md
- https://github.com/gcanti/fp-ts/blob/master/docs/modules/ReaderTaskEither.ts.md
- https://github.com/gcanti/fp-ts/blob/master/docs/modules/TaskThese.ts.md

**Comment by sobolevn** [comment]
We also would probably need things like:

- `TaskResult`
- `RequiresContextTaskResult`

I consider all tasks to be `IO` bound. Is it a good idea?

**Comment by SaschaSchlemmer** [comment]
I'd not consider everything IO, and I'd also avoid the name `Task` for something like demonstrated above; the reason being that this proposal is not about tasks (order of execution, handling failures, parallel/concurrently running tasks) just about adding functional syntactic sugar around `async` and `await` independent of any specific library for dealing with scheduling (like asyncio, trio, twisted, etc. )

**Comment by sobolevn** [comment]
Fair enough about `Task`. 

What's your opinion about not being `IO`? Are there any valid cases to create a coroutine that does not do any `IO`?

**Comment by SaschaSchlemmer** [comment]
Yes, there are definitely use cases where coroutines are not just used for IO; in particular there is `concurrent.Futures.ProcessPoolExecutor` which is used to run synchronous code in parallel (true parallelism with multiple processes).

**Comment by SaschaSchlemmer** [comment]
I've got a couple of examples that help to better understand what this whole synchronous vs asynchronous/concurrent vs parallel business is all about (and how this would look like using `Promise`). For this I modified my simple functions from above as follows:

```python
def double(x: int) -> int:
    time.sleep(1)
    return 2*x
    
async def double_async(x: int) -> int:
    await asyncio.sleep(1)
    return 2*x
```
---
### Test cases:

1. Running computations sequentially (aka. synchronous code)
    ```python
    tic = time.perf_counter()
    await (
        Promise(coro([1,2,3]))
        .map(partial(map, double))
        .map(list)
    )
    toc = time.perf_counter()

    print(toc-tic)  # 3 seconds
    ```
2. Running computations concurrently (aka. asynchronous code)
    ```python
    tic = time.perf_counter()
    await (
        Promise(coro([1,2,3]))
        .map(partial(map, double_async))
        .bind(star_gather)
        .map(list)
    )
    toc = time.perf_counter()

    print(toc-tic)  # 1 second
    ```
3. Running computations in parallel (aka. multiprocessing)
    ```python
    tic = time.perf_counter()
    with concurrent.futures.ProcessPoolExecutor() as pool:
        await (
            Promise(coro([1,2,3]))
           .map(partial(pool.map, double))
           .map(list)
    )
    toc = time.perf_counter()

    print(toc-tic)  # 1 second
    ```

**Comment by SaschaSchlemmer** [comment]
Notice that I added another usage example at the bottom of my original post :)

**Comment by SaschaSchlemmer** [comment]
Also it appears typing with mypy works out of the box (and without requiring a plugin):

```python
from __future__ import annotations
from typing import Generic, TypeVar, Callable, Awaitable

A = TypeVar('A')
B = TypeVar('B')


class Continuation(Generic[A]):

    def __init__(self, coro: Awaitable[A]):
        self._coro = coro

    @classmethod
    def unit(cls, value: A) -> Continuation[A]:
        async def coro() -> A:
            return value
        return cls(coro())

    def map(self, f: Callable[[A], B]) -> Continuation[B]:
        async def coro() -> B:
            x = await self._coro
            return f(x)
        return Continuation(coro())

    def bind(self, f: Callable[[A], Awaitable[B]]) -> Continuation[B]:
        async def coro() -> B:
            x = await self._coro
            return await f(x)
        return Continuation(coro())

    def __await__(self):
        return self._coro.__await__()
```
After some googl'ing around I came to the conclusion that `Promise` also isn't a good name because it is used in _javascript_ for a similar but different concept. In _haskell_ there is [`Cont`](https://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Cont.html) which is (as far as I understood) exactly what I am proposing here.

**Comment by sobolevn** [comment]
Yes, I like `Continuation` the most! Will you send a PR for this? 

And we can start a detailed discussion from there.

**Comment by SaschaSchlemmer** [comment]
Over the weekend I will probably have some spare time to work on this :) I also played around with lists of continuations (I implemented another monad `ListContinuation` that works over multiple continuations) because running multiple things at the same time is usually what async code is all about. I don't know what your take is on more specialized monads, monad transfomers and extensible effects for nesting monads inside one another.

**Comment by sobolevn** [comment]
Related https://github.com/correl/typesafe-monads/blob/master/monads/future.py

**Comment by SaschaSchlemmer** [comment]
Sry for not responding for a while, been very busy; seems to me the code you linked does basically the same and adds some features my proposal didn't have as well.

**Comment by sobolevn** [comment]
I have created an issue in the `typesafe-monads` repo. Maybe we can collaborate on this one?

**Comment by SaschaSchlemmer** [comment]
That sounds like a good idea

**Comment by sobolevn** [comment]
I also like the idea that `Future[A]` contains `IO[A]` inside as a value. And you cannot construct pure `Future` instance. That's how it is in `fp-ts`: https://gcanti.github.io/fp-ts/modules/Task.ts.html

And that's how Python really works. You cannot just can a coroutine. You have to use an executor like `asyncio.run` or do some magic. It is not pure.

I also like this idea, because it will simplify the implementation. No need for separate `Future` vs `FutureIO` vs `FutureResult` vs `FutureIOResult`. There would be only two types: `FutureResult` and `Future` for computations that can and cannot fail.

**Comment by sobolevn** [comment]
Ok, maybe `Future` is not the best name https://docs.python.org/3/library/asyncio-future.html#asyncio.Future

**Comment by sobolevn** [comment]
Really interesting project https://github.com/h2non/paco

**Comment by sobolevn** [comment]
We would also need to rework:
- `@safe` decorator, related #333 
- `@maybe` decorator
- `@impure` decorator

**Comment by sobolevn** [comment]
After playing around `asyncio` and `Future` a bit, I would say that a correct way to handle this would be:

1. Drop all `async` functions we have
2. Forbid to use `async` keyword in `wemake-python-styleguide` and ban `import asyncio`
3. Close this issue
4. Burn everything with fire! 🔥

**Comment by sobolevn** [comment]
Related #355

**Comment by sobolevn** [comment]
5. Switch back to python2.7

**Comment by NovemberOscar** [comment]
Can we have a type safe Monad transformers like OptionT and ResultT for easy dealing with Future? 

Most of real-world problems have to dealing with Future of (Option, Result, Either, etc)

I implemented [ResultFuture](https://github.com/NovemberOscar/playground/blob/master/python-monad/main.py#L14-L27) . (but technically, this is not a **real** monad transformer. )



ref: https://medium.com/coding-with-clarity/practical-monads-dealing-with-futures-of-options-8260800712f8
ref2: https://typelevel.org/cats/datatypes/eithert.html

**Comment by sobolevn** [comment]
@NovemberOscar yes, we will have `Future[a]`, `FutureResult[a, b]`, `FutureMaybe[a]`, `RequiresContextFutureResult[e, a, b]`

Where `await Future[a] -> IO[a]`. We need this `IO` layer because otherwise the amount of monads we need to implement will simply blow up. And I don't see any valid reasons to use `asyncio` for not doing `IO`. And futures do look pure for me. So, this is reasonable I hope. 

There would be helpful composition methods for each `Future`-based monad to compose functions without struggling with an extra `IO` layer.

**Comment by sobolevn** [comment]
First prototype (it is too early to make a PR, but you can already play with it):

```python
from abc import ABCMeta
from functools import wraps
from inspect import iscoroutinefunction
from typing import (  # noqa: WPS235
    Any,
    Callable,
    ClassVar,
    Coroutine,
    Generic,
    Type,
    TypeVar,
    Union,
    overload,
    Awaitable,
    Iterator,
    Generator,
)

from typing_extensions import final

from returns.io import IO, impure
from returns.primitives.container import BaseContainer
from returns.primitives.exceptions import UnwrapFailedError

# Definitions:
_ValueType = TypeVar('_ValueType', covariant=True)
_NewValueType = TypeVar('_NewValueType')
_ErrorType = TypeVar('_ErrorType', covariant=True)
_NewErrorType = TypeVar('_NewErrorType')
_ContraErrorType = TypeVar('_ContraErrorType', contravariant=True)

# Aliases:
_FirstType = TypeVar('_FirstType')
_SecondType = TypeVar('_SecondType')

# Composition helpers

async def async_identity(instance: _FirstType) -> _FirstType:
    return instance


async def _async_map(
    function: Callable[[_ValueType], _NewValueType],
    inner_value: Awaitable[_ValueType],
) -> _NewValueType:
    return function(await inner_value)


async def _async_bind_awaitable(
    function: Callable[[_ValueType], Awaitable[_NewValueType]],
    inner_value: Awaitable[_ValueType],
) -> _NewValueType:
    return await function(await inner_value)


async def _async_bind(
    function: Callable[[_ValueType], 'Future[_NewValueType]'],
    inner_value: Awaitable[_ValueType],
) -> _NewValueType:
    return (await function(await inner_value))._inner_value


async def _async_bind_async(
    function: Callable[[_ValueType], Awaitable['Future[_NewValueType]']],
    inner_value: Awaitable[_ValueType],
) -> _NewValueType:
    return await (await function(await inner_value))._inner_value


@final
class Future(Generic[_ValueType]):
    _inner_value: Awaitable[_ValueType]

    def __init__(self, inner_value: Awaitable[_ValueType]) -> None:
        self._inner_value = inner_value

    def __await__(self) -> Generator[Any, Any, IO[_ValueType]]:
        return self.awaitable().__await__()

    async def awaitable(self) -> IO[_ValueType]:
        return IO(await self._inner_value)

    def map(
        self,
        function: Callable[[_ValueType], _NewValueType],
    ) -> 'Future[_NewValueType]':
        return Future(_async_map(function, self._inner_value))

    def bind(
        self,
        function: Callable[[_ValueType], 'Future[_NewValueType]'],
    ) -> 'Future[_NewValueType]':
        return Future(_async_bind(function, self._inner_value))

    def bind_async(
        self,
        function: Callable[[_ValueType], Awaitable['Future[_NewValueType]']],
    ) -> 'Future[_NewValueType]':
        return Future(_async_bind_async(function, self._inner_value))

    def bind_awaitable(
        self,
        function: Callable[[_ValueType], 'Awaitable[_NewValueType]'],
    ) -> 'Future[_NewValueType]':
        return Future(_async_bind_awaitable(function, self._inner_value))

    @classmethod
    def from_value(cls, inner_value: _NewValueType) -> 'Future[_NewValueType]':
        return Future(async_identity(inner_value))
```

Example:

```python
from returns.future import Future
from returns.io import IO
import asyncio
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    reveal_type = print

async def test(x: int) -> int:
    return x + 1

def with_future(x: int) -> Future[int]:
    return Future.from_value(x + 1)

async def async_future(x: int) -> Future[int]:
    return Future.from_value(x + 1)

async def main() -> IO[int]:
    return await Future.from_value(2).bind_awaitable(test).bind(with_future).bind_async(async_future)

reveal_type(asyncio.run(main()))
```

mypy and python:

```
(.venv) ~/Documents/github/returns  master ✗                                      1 ⚠️
» mypy ex.py
ex.py:21: note: Revealed type is 'returns.io.IO*[builtins.int]'

(.venv) ~/Documents/github/returns  master ✗                                      1 ⚠️
» python ex.py
<IO: 5>
```

Any feedback is welcome on this stage! Especially:

1. Naming, it is hard. I would love to hear other possible name variants for methods
2. Performance (as you can see I have moved the coroutines from the method definition. Maybe there's something else to improve? 
3. Usability
4. Typing

**Comment by sobolevn** [comment]
TODO for `Future`:

- [ ] type tests
- [ ] `@future` decorator
- [ ] regular tests (including interfaces, and `trio`-based tests)
- [ ] docs

**Comment by sobolevn** [comment]
These methods are left to finish `RequiresContextFutureResult`:

- [ ]  `def bind_future(self, function): ...`
- [ ]  `def bind_future_result(self, function): ...`
- [ ]  `def bind_async_future(self, function): ...`
- [ ]  `def bind_async_future_result(self, function): ...`
- [ ]  `def bind_context_ioresult(self, function): ...`
- [ ]  `def bind_async(self, function): ...`
- [ ]  `def bind_awaitable(self, function): ...`

We also need to provide `ContextFutureResult` with `.ask` method

**Comment by sobolevn** [comment]
Unit methods:

- `.from_io` (both to `ReaderIOResult` and `ReaderFutureResult`)
- `.from_future`
- `.from_future_result`
- `.from_ioresult_context`

**Comment by sobolevn** [comment]
Pointfree:

 - [ ] `bind_async_future`
 - [ ] `bind_async_future_result`
