### ISSUE TITLE
Our `Immutable` type should support `__copy__` and `__deepcopy__` methods

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#276]
Currently our definition of `Immutable` misses these two methods:

```python
class Immutable(object):
    def __copy__(self):
        return self

    def __deepcopy__(self, memo):
        return self
```

**Comment by phakiller** [comment]
I can take this!

Just to clarify, the code snippet is not the final implementation, right?

**Comment by sobolevn** [comment]
It looks like it is. We already have `Immutable` class in `types.py`.
