### ISSUE TITLE
Consider `Maybe` methods that state if a value is present/absent

### ISSUE THREAD

**Issue by homeworkprod** [dry-python/returns#278]
Hi,

I'm just getting my feet wet with `returns`. As a first iteration, I'm trying to introduce `Maybe` into a somewhat larger codebase of mine.

One thing that irks me a bit is code like this:

Coming from code like this:
```py
item: Optional[Item] = find_item(item_id)
if item is None:
    raise SomeCustomException("ohai")
```

(Naively) porting to `Maybe` leaves me with this:
```py
item: Maybe[Item] = find_item(item_id).value_or(None)
if item is None:
    raise SomeCustomException("ohai")
```

While I can replace `is not None` checks after which I want to process the value with `Maybe.map` (and not raise an exception if the value is missing) and gain more succinct code, almost the opposite seems to be the case if I don't want to work with the potential value but rather its existence itself.

Another example:
```py
# traditional
token: Optional[Token] = find_token(some_key)
valid_token_found: bool = (token is not None) and not token.is_expired

# `returns`-y way
from returns.maybe import Some
token: Maybe[Token] = find_token(some_key)
valid_token_found: bool = token.map(lambda t: not t.is_expired) is Some
```

**What I'm looking for** is a method like `[is_]{present, absent, some, none}`, `has_value`, `empty`, etc. to allow me to do this:
```py
# `returns`-y way
# NB: No import necessary!
token: Maybe[Token] = find_token(some_key)
valid_token_found: bool = token.map(lambda t: not t.is_expired).present
```

Am I overlooking some best practice that avoids imports and identity/equality operators? If not, are you open to consider adding such (potentially even more auto-complete-friendly) methods?

Thanks!

**Comment by sobolevn** [comment]
Hi @homeworkprod! Thanks a lot for your interest in `returns`!

Considering your feature request, by design Python does not allow us to override `is` operation. Because, it should serve the only purpose: tell if object is the same one in memory. We cannot override this.

But, I see another ways to achieve your goals here:

```python
from returns.maybe import Maybe
from returns.pipeline import is_successful

token: Maybe[Token] = find_token(some_key)
valid_token_found = is_successful(token.map(lambda t: not t.is_expired))
```

And:

```python
item: Maybe[Item] = find_item(item_id)
if not is_successful(item):
    raise SomeCustomException("ohai")
```

Does this work for you?

**Comment by homeworkprod** [comment]
Hi @sobolevn, thank you for your quick response.

My intent is not to override `is` for this use case.

While `is_successful` technically works, I see a few downsides:
- It requires an import to use it.
- It doesn't auto-complete.
Both make it relatively hard to use for someone unfamiliar with *returns*.

From my experience with introducing `Optional` (both Guava's and Java 8's) into multiple rather big Java code bases I've learned that acceptance with people is higher if they don't have to figure out too much. Pressing the auto-complete hotkey usually worked well; but having them to know to import something, and what exactly, and to do actually that would be a burden resulting in animosity towards the introduction of such a data structure and concept, and developers trying to introduce it :)

I'm not requesting something super special here, but rather something I'm familiar with from other environments. For example:
- Haskell's `Maybe` has [`isJust`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Maybe.html#v:isJust) and [`isNothing`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Maybe.html#v:isNothing)
- Guava's `Optional` has [`isPresent`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Optional.html#isPresent--) (but no counter-part; [discussion](https://github.com/google/guava/issues/734))
- Java's `Optional` has [`isPresent`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#isPresent()) and (as of Java 11) [`isEmpty`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#isEmpty())
- Scala's `Option` has [`isDefined`](https://www.scala-lang.org/api/current/scala/Option.html#isDefined:Boolean) and [`isEmpty`](https://www.scala-lang.org/api/current/scala/Option.html#isEmpty:Boolean)
- Rust's `Option` has [`is_some`](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some) and [`is_none`](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_none)

**Comment by homeworkprod** [comment]
Okay then.

I guess `is_some` and `is_nothing` are the obvious choice since *returns*' `Maybe` consists of `Some` and `Nothing`?

**Comment by homeworkprod** [comment]
A quick PR to add this: #300

**Comment by homeworkprod** [comment]
Regarding the part where code would currently throw an exception, an equivalent of Java's [`orElseThrow(Supplier)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#orElseThrow(java.util.function.Supplier))¹ might be handy.

For example:
```py
item: Optional[Item] = find_item(item_id)
if item is None:
    raise SomeCustomException("ohai")
```
could become:
```py
item: Item = find_item(item_id) \
    .value_or_raise(lambda: SomeCustomException("ohai"))
```

Then again, I'm not sure if this is really a good idea or if it can be reasoned that this becomes unnecessary if one would be using `Result`.

---

¹) Both the methods to get a value as well as those to throw an exception if the container value is absent have a form each that accepts a supplier to generate a value/exception lazily.

Should `Maybe.value_or` get a sibling that accepts a lazy callable as well? (Overloading doesn't work in Python, and treating `value_or`'s argument as lazy callable if it's a callable breaks callables as default values.)

**Comment by sobolevn** [comment]
`fp-ts` uses this approach: https://github.com/gcanti/fp-ts/blob/master/src/Option.ts#L231-L262

**Comment by sobolevn** [comment]
I like `.or_else(lambda: call())` version.
1. It is unique for `Maybe`, because the callable does not accept any error argument, unlike `.rescue` which does accept one
2. This name is quite common in similar libraries

**Comment by homeworkprod** [comment]
There are three fallback cases (i.e. when the `Maybe` contains no value) I'm familiar with:
1. Return a static value.
2. Call a callable to lazily obtain a value.
3. Raise an exception.

I don't see how we could combine cases 1 and 2 in Python; `.or_else(lambda: 42)` would seem only half-done to me.

> This name is quite common in similar libraries

It is indeed, but usually for case 1.

**Comment by sobolevn** [comment]
Great questions! 

1. We have `.value_or` for this actually, it works like this: `assert Nothing.value_or(1) == 1 and Some(0).value_or(1) == 0`
2. That's exactly what `.or_else` does! `assert Nothing.or_else(lambda: 1) == 1 and Some(0).or_else(lambda: 1) == 0` 
3. We can use composition to achieve this: 

```python
from returns.functions import raise_exception

Nothing.or_else(lambda: raise_exception(ValueError('missing!')))
# Traceback: ValueError('missing!')
```

**Comment by homeworkprod** [comment]
I know about `value_or`; I've mentioned it above and it's the reason I used `value_or_raise` in [my suggestion](https://github.com/dry-python/returns/issues/278#issuecomment-608138827).

My (hidden) point is: Having both `value_or` and `or_else` – which one does what exactly, judging from the name? Seems to me that people could mix them up *a lot*.

For example, names `value_or` and `value_or_call` would be more clear and consistent (and auto-complete can show both as they have the same prefix).

Regarding 3:
Doable, but very bulky IMHO. One could even argue that your `or_else` suggestion could also be a function `fallback_lazily(maybe, callable)` one has to import.

**Comment by sobolevn** [comment]
`or_else_call` sounds great! 👍
