### ISSUE TITLE
Add `not_` function

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#313]
It should work like so:

```python
assert not_(is_successful)(Success(1)) is False
assert not_(is_successful)(Failure(1)) is True
```

Related #300 
Related #301

**Comment by thepabloaguilar** [comment]
Is this issue ready for development or we have to wait the two related PRs?

**Comment by sobolevn** [comment]
Yes, this is completely ready. Please, feel free to take it.

**Comment by thepabloaguilar** [comment]
So, I'll take it!!
