### ISSUE TITLE
Unexpected behavior of `Some(None)`

### ISSUE THREAD

**Issue by homeworkprod** [dry-python/returns#314]
I expect the `Some` "constructor" (actually just a function) to only return `Some`s.

However, given `None`:
```py
>>> from returns.maybe import Some
>>> Some(None)
<returns.maybe._Nothing object at 0x7f345dcaa1c8>
```

For reference, another language that has null pointers, Java, raises an exception on `Optional.of(null)`.

In general, I expect the explicitly requested creation of a `Some` to fail if no actual value to wrap in it is supplied.

If one explicitly wants to let `Maybe` decide whether to create a `Some` or `None` given a thing, there still is `Maybe.new` (to which `Some` just delegates).

**Comment by astynax** [comment]
Should stay `Some(None)` definitely.

**Comment by homeworkprod** [comment]
@astynax, thanks for looking into it.

However, I'm quite confused about your verdict, to be honest.

As I understand the [option type](https://en.wikipedia.org/wiki/Option_type), the two states it represents are either nothing or a present value.

`Some(None)` however would be a container that wraps nothing.

Pattern matching is a popular choice to unwrap a maybe/an option type, like this (example from Wikipedia page mentioned earlier):
```haskell
-- This function uses pattern matching to deconstruct Maybes
compute :: Maybe Int -> String
compute Nothing  = "No value"
compute (Just x) = "The value is: " ++ show x
```

The equivalent of `Some(None)` can not even be represented in Haskell (correct me if I'm wrong). `Just Nothing` is possible, but the *returns* equivalent is `Some(Nothing)`, but *not* `Some(None)`.

The whole point of a "something" object is to guarantee that it contains something. `None` is not something.

Also, the docstring of *returns*' [`_Some` class](https://github.com/dry-python/returns/blob/master/returns/maybe.py#L244) states:
`Represents a calculation which has succeeded and contains the value.`
I think it's clear that `None` in Python world is not a value.

I might be overlooking something here, but `Some(None)` seems totally unacceptable to me.

Is it possible you meant `Some(Nothing)` instead? Because that is something I think would make sense. Then again, I would only allow it to be constructed via `Some(Nothing)`, but not as a fallback for `Some(None)` – which, to me, still is an invalid value to pass to `Some`, and worth a `TypeError` or `ValueError` to be raised.

**Comment by astynax** [comment]
@homeworkprod `NoneType` is not "nothing". Is is a inhabitated type with one value, i.e. *unit type*. In terms of Haskell `Some(None)` is `Just ()`.

**Comment by sobolevn** [comment]
My idea was that you might sometime need to explicitly represent that real `None` exists somewhere. Think of this example:

```
d = {'a': 1, 'b': None}
md = maybe(d.get)

a = md('a')  # Some(1)
b = md('b')  # Some(None)
c = md('c')  # Nothing
```

We can see that 'b' and 'c' are different. And previously it was impossible to tell this difference. Now it is.

**Comment by sobolevn** [comment]
On the other hand I understand that `Some(None)` might be very confusing for people. That's why I did allow this type in the previous versions.

**Comment by astynax** [comment]
`Nothing` - absence of value,
`None` - actual value with zero bits of information, but still existing one.

`md('b') == Some(None)` means "value exists but stores no information",
`md('c') == Noting` means "there is no value for this key".

Here we have a solutions for problem "`get` returned `None` but what it means: no value or value is None?"

BTW, `maybe(d.get)` looses this information.

**Comment by sobolevn** [comment]
This should go to the docs. 👍

**Comment by sobolevn** [comment]
Nope, this won't do. 

```python
from returns.maybe import Some, Nothing, Maybe, maybe

source = {'a': 1, 'b': None}
def md(key: str) -> Maybe[int]:
    try:
        return Some(source[key])
    except KeyError:
        return Nothing

reveal_type(md('a'))  # ok: Revealed type is 'returns.maybe.Maybe[builtins.int]'
reveal_type(md('b').unwrap())  # not ok: Revealed type is 'builtins.int*'
```

Because in real life `md('b').unwrap()` would be `None`. And I don't want to have `Maybe[Optional[int]]` this is rally ugly.

Proposed solution: use `Result` when you care about value / `None`/ error things.
Like so:

```python
from returns.result import safe

source = {'a': 1, 'b': None}

@safe
def md(key: str) -> int:
    return source[key])

reveal_type(md('a'))  # Revealed type is 'returns.result.Result[builtins.int, Exception]'
reveal_type(md('b').unwrap())  # ok: Revealed type is 'builtins.int*'
```

We would have:

- `Success(1)` or `Success(None)` for `'a'` and `'b'`
- `Failure(KeyError)` for `'c'`

We can always use `result_to_maybe` or `maybe_to_result` converters.
