### ISSUE TITLE
Working with non-monadic functions

### ISSUE THREAD

**Issue by lainiwa** [dry-python/returns#319]
What is the conventional way of lifting a 2-adic (and more) function to accept impure arguments?

For example:
```python
def div(a: int, b: int) -> int:
    return a / b

a = IO(10)
b = IO(5)

# How do I apply div here?
```

The best I could come up with is

```python
from toolz.functoolz import curry

f = curry(div)
f1 = a.bind(f)
f2 = b.bind(f1)

print(f2)
```

This turns into more boilerplate for functions with higher arity, and it cannot (as it seems to me) be simplified with return's pipelines.

Is there a better workaround?

**Comment by sobolevn** [comment]
Hi, @lainiwa! Working with functions with more than one monadic argument is hard.

There are several work-around:
1. You can use `io_squash` if you are working with `IO` monad
2. You can wait (or even help!) with our currying implementation: #267 
3. You can use `.pipeline()` if you are working with `Result` or `Maybe` monads

**Comment by lainiwa** [comment]
Squashing arguments seems a viable alternative! Might it be convinient to have a helper function in returns for this? Kind of:

```python
from returns.converters import squash_io

def apply_multiple(fun, *args):
    new_fun = lambda tpl: fun(*tpl)
    return squash_io(*args).bind(new_fun)

print(apply_multiple(div, a, b))
```

A real-world function should probably somehow handle a mixture of IO and non-IO arguments, though.

I guess it might save a bit of typing for users of returns.

**Comment by sobolevn** [comment]
@lainiwa you would love to accept this PR if the typing would be fine.

**Comment by sobolevn** [comment]
Done, `.apply` is ready, `curry` is ready.
