### ISSUE TITLE
Consider adding `apply` method

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#342]
I didn't want to invite applicatives and functors on our small party here.
Because learning `apply` concepts can be troublesome for some people.
And working with wrapped functions is really hard without currying. Because it soon will become: 

```python
>>> Some(3).apply(Some(2).apply(Some(1).map(lambda a: lambda b: lambda c: a + b + c)))
<Some: 6>`
```

With curry it can become something like this:

```python
@curry
def some_three(a: int, b: int, c: int) -> int:
     return a + b + c

>>> Some(3).apply(Some(2).apply(Some(1).map(some_three)))
```

But, we already have `.from_value` protocol defined. And `@curry` will be added in #341 
So, it might be worth adding this new concept.

**Comment by phakiller** [comment]
@sobolevn Do you need some help on this issue?

**Comment by sobolevn** [comment]
This issue will be in work after we will create typed `@curry` decorator. I will ping you later 🙂

**Comment by phakiller** [comment]
Don't worry, I'll take another issue!

**Comment by sobolevn** [comment]
Pointfree functions are not yet implemented.

**Comment by sobolevn** [comment]
Related #380 
Related #376
