### ISSUE TITLE
Add `.bind_io` method to `IOResult`

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#349]
This way it would be really easy to compose these two:

```python
io = IO(1)
io_res = IOSuccess(2)

iores.bind_io(lambda x: io.map(lambda y: x + y))
```

**Comment by thepabloaguilar** [comment]
I'll take this one, if possible!

**Comment by sobolevn** [comment]
I have already implemented this one, sorry! 👍

**Comment by thepabloaguilar** [comment]
> I have already implemented this one, sorry! 👍 

No problem!
