### ISSUE TITLE
@safe, @maybe, @impure, etc decorators should work with generators

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#355]
Currently it is impossible to work with generator functions with `@safe` and other decorators.

We need to fix that.
Async generators are currently out of scope.

**Comment by sobolevn** [comment]
Currently it reports incorrect type:

```python
from returns.result import safe
from typing import Iterator

@safe
def test(arg: int) -> Iterator[int]:
    yield arg +1

reveal_type(test(6))
```

Output:

```
» mypy ex.py --show-traceback
ex.py:9: note: Revealed type is 'returns.result.Result[typing.Iterator*[builtins.int], builtins.Exception]'
```

Should be:

```
» mypy ex.py --show-traceback
ex.py:9: note: Revealed type is 'typing.Iterator[returns.result.Result[builtins.int, builtins.Exception]]'
```

**Comment by sobolevn** [comment]
> Should be:

Or not. This is very different use-case. I need to dig it deeper.

**Comment by thepabloaguilar** [comment]
About the `@safe`, I think it's the correct behavior!
Because `@safe` wraps the function with a `try...except`, if the function executes correctly `@safe` will return a `Success` container containing our `Iterator` otherwise it'll return a `Failure` container containing an `Exception`.

**Comment by sobolevn** [comment]
Yes, I think so too.

**Comment by sobolevn** [comment]
Yes, this should be something different.
