### ISSUE TITLE
@pipeline signature changed

### ISSUE THREAD

**Issue by ydanilin** [dry-python/returns#361]
Hello! I like the way ```returns``` library works and use it in production! (My code is NDAed so it is not open). I enjoy to use ```@pipeline``` decorator most of all.

The only thing made me confused is that ```@pipeline``` signature was changed after 0.11.0 suddenly (now requires mandatory argument) - means backward compatibility broken, no deprecation warnings were shown...

I understand that it is somehow my fault not to pin the versions strictly - I moved from Anaconda env manager (where they were pinned) to Poetry and just decided to install latest versions for all libs )). 

**But is it correct to break backward compatibility without any notice or do not I understand something?**

**Comment by sobolevn** [comment]
Hi, @ydanilin! Thanks a lot for using `returns`.

Currently we are pushing limits of Python hard enough to make lots of mistakes in the process. So, we have to fix them. And sometimes they do require to break the public API.

We do a couple of things to help our users:
1. We write all breaking change on top of our CHANGELOG: like the one for `@pipeline` https://github.com/dry-python/returns/blob/master/CHANGELOG.md#features-2
2. We mark our software as `beta`: https://github.com/dry-python/returns/blob/master/pyproject.toml#L38
3. We use `0-based` version to mark that API is not stable 
4. We ship all `mypy` type to be able to check that something is broken without even running your code, it makes it really easy to catch all breaking changes even in CI with tools like @dependabot-bot 

Currently we will continue to break things in each release before we reach `1.0`. Sorry for the inconvenience.

**Comment by ydanilin** [comment]
@sobolevn thank you for your reply, now I understand it better.

Regarding point 4: I did not adopt mypy in my work yet. I can google or read the docs but maybe do you know some good practical tutorials how to enter into mypy world?

**Comment by sobolevn** [comment]
I guess the official docs are the best way to learn: https://mypy.readthedocs.io/

And I highly recommend to use `returns` with `mypy`. Otherwise, you will lose lots of cool features we have! 👍
