### ISSUE TITLE
Add `is_result` function

### ISSUE THREAD

**Issue by thepabloaguilar** [dry-python/returns#365]
It should return `True` for `Result`, `FutureResult`. `RequiresContextResult`, `ContextResult`, `RequiresContextIOResult` and `ContextIOResult`

**Comment by thepabloaguilar** [comment]
I'll take this one!

**Comment by sobolevn** [comment]
@thepabloaguilar Hi! Thanks a lot for taking your time and working on this.

I have decided that we are not going to need these methods. Let me explain you the whole picture.

Once I was writing a really ugly wrapper around a legacy script that had this signature: `Union[_ValueType, IO[_ValueType], IOResult[_ValueType, ...]]`
And I wrote it like this: `if isinstance(container, (IO, IOResult)): ...`
Then I recognised that it can be a new feature. That's how `is_io` was born. 
Then it seemed logical to me to have other checks as well.

But now I am thinking: why would anyone would love to have it? The whole point of this project is to remove things like `isinstance` and other checks. Moreover, our own API and types are not mature enough to work with `IO` and `IOResult` with the same codebase. 

So, it is just pointless. 😞 

Sorry for all the fuzz and long thinking about this problem. 

Cheers, 
Nikita

**Comment by thepabloaguilar** [comment]
No problem man!

**Comment by thepabloaguilar** [comment]
I'll close the PR #366!

**Comment by sobolevn** [comment]
❤️ 🍻
