### ISSUE TITLE
No attribute `Maybe.from_value` returns version 0.13.0

### ISSUE THREAD

**Issue by dgjustice** [dry-python/returns#373]
```python
>>> from returns.maybe import Maybe
>>> Maybe.from_value(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Maybe' has no attribute 'from_value'
>>>
```

It looks like it has been renamed to `Maybe.new`, but I can't find any mention of it in the docs.

```python
>>> Maybe.new(None)
<returns.maybe._Nothing object at 0x7f933784c6e0>
>>> str(Maybe.new(None))
'<Nothing>'
>>>
```

**Comment by sobolevn** [comment]
@dgjustice thanks a lot! 

In `0.13` we had `Maybe.new`, `Result.from_success`, etc. Which was very wrong. 
Now in `0.14` (which is not yet released) we have `.from_value` supported for all containers. 

In case the `latest` docs are misleading you, can use https://returns.readthedocs.io/en/0.13.0/

**Comment by sobolevn** [comment]
Also see our changelog: https://github.com/dry-python/returns/blob/master/CHANGELOG.md#0140-wip

**Comment by sobolevn** [comment]
I am going to close this as resolved. In case you have any other questions, please, ask them. Or feel free to reopen this issue if you still want us to improve something 🙂

**Comment by dgjustice** [comment]
Awesome, thanks for clarifying.  This is a great project, I'm hoping to use it soon in my own work!

**Comment by sobolevn** [comment]
@dgjustice I would love to hear your feedback after some time in production. I really recommend to wait for `0.14` release, it is going to be awesome!
