### ISSUE TITLE
Improve Failure tracibility 

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#409]
`dry-rb` has a cool feature: tracing failures https://dry-rb.org/gems/dry-monads/1.3/tracing-failures/
We need something similar to improve debugging experience. It might be included into the core, or just into some `contrib/` package.

**Comment by thepabloaguilar** [comment]
I've made some studies to introduce that feature, maybe we can add one more attribute do `BaseContainer`.

```python
class BaseContainer(Immutable, metaclass=ABCMeta):
    """Utility class to provide all needed magic methods to the context."""

    __slots__ = ('_inner_value', '_trace')
    _inner_value: Any
    _trace: str

    def __init__(self, inner_value, trace="") -> None:
        """DOC"""
        object.__setattr__(self, '_inner_value', inner_value)  # noqa: WPS609
        object.__setattr__(self, '_trace', trace)  # noqa: WPS609

    # CODE
```

Modifies `_Failure` initializer:
```python
@final
class _Failure(Result[Any, _ErrorType]):
    """DOC"""

    _inner_value: _ErrorType

    def __init__(self, inner_value: _ErrorType, trace: str) -> None:
        """DOC"""
        super().__init__(inner_value, trace)
```

And finalizing `Failure` function:
```python
def Failure(  # noqa: N802
    inner_value: _NewErrorType,
) -> Result[Any, _NewErrorType]:
    """DOC"""
    caller = stack()[1]
    trace = "{0}:{1} in `{2}`".format(caller.filename, caller.lineno, caller.function)
    return _Failure(inner_value, trace)
```

My idea putting `Failure` function to get the caller function is because it knows who's calling it and this is much easier than make `BaseContainer` or `Result` classes know who's calling!
I made a test and the output was:
```sh
/home/pabloaguilar/Projects/returns/tests/test_result/test_result_equality.py:71 in `test_immutability_failure`
```

**Comment by sobolevn** [comment]
Great research! Thanks a lot!

I would say that one of the most important requirements here is performance. We cannot slow down `Failure` call for people who is not using this feature. 

That's why I though about making a property like this:

```python
class _Failure(...):
    @property
    def trace(self):
        ...
```

What do you think?

**Comment by thepabloaguilar** [comment]
I have a question, I don't know much about `dry-rb`. Does trace show where `Failure` is created or the `.trace` method is called?

**Comment by thepabloaguilar** [comment]
I think it's nice using a `@property`, but to be equal than `dry-rb` we have to show where `Failure` was created. We just have this information when we on top of the call stack!
Using a function/method to get that information later we won't have access anymore to the old call stack when creation was called!

**Comment by thepabloaguilar** [comment]
Looking to `dry-rb` implementation, it sets the value at instantiation time. [Reference](https://github.com/dry-rb/dry-monads/blob/f7d91fe552b24ae787cc229d52ea6e5ab750cea3/lib/dry/monads/result.rb#L172)

**Comment by thepabloaguilar** [comment]
I have studied a bit of `CPython` code to take care of the performance issue that can appear, and I achieve some points to help us:

* [stack(..)](https://github.com/python/cpython/blob/master/Lib/inspect.py#L1538) is just a wrapper to get all the frames above current frame, **we don't need this**
* *stack(...)* uses [getouterframes(...)](https://github.com/python/cpython/blob/0383be4666905f9e24ca791afda845a7686b3fe3/Lib/inspect.py#L1510) that has important information, it just handles a frame and iterates over the "stack" using *f_back* frame attribute to get the information from all frames above.
* *getouterframes(...)* uses [getframeinfo(...)](https://github.com/python/cpython/blob/0383be4666905f9e24ca791afda845a7686b3fe3/Lib/inspect.py#L1471), in this function we can see how information is extracted from a frame we don't need all the information.

In resume, we can implement like this:
```python
import sys

frame = sys._getframe(1)
print(f"{frame.f_code.co_filename}:{frame.f_lineno} in `{frame.f_code.co_name}`")
```

`sys` module is implemented in `C`, and you can see the implementation of *sys._getframe(...)*  [here](https://github.com/python/cpython/blob/0383be4666905f9e24ca791afda845a7686b3fe3/Python/sysmodule.c#L1786).

I think it won't denigrate the performance to users that no uses `trace`!

What do you think @sobolevn??

**Comment by sobolevn** [comment]
@thepabloaguilar let's measure it! We can try the basic `timeit` for the start

**Comment by thepabloaguilar** [comment]
Do you have other tests in mind than just:
```python
Failure("some_inner_value")
```

I'm going to make theses tests ASAP

**Comment by sobolevn** [comment]
Related types like `IOResult` and context-related results. We also have quite a lot of methods like `.from_failed_*` that does internally rely on `Failure`.

**Comment by thepabloaguilar** [comment]
Ok, first of all, I'll test only `Failure` container. Because if we have bad results using it naturally others one will have too!

**Comment by thepabloaguilar** [comment]
Code used to tests:
```python
if __name__ == '__main__':
    import timeit

    print(timeit.repeat("Failure('inner_value')", repeat=10, number=10000, globals=globals()))
```

Times for *Failure* **without** trace:
```text
0.009887706999961665
0.009061151999958383
0.008264703999998346
0.008208331999981056
0.008230599999933474
0.008188849000021037
0.008247498999935488
0.00826892999998563
0.008196945000008782
0.008180051000067579
```
Average: 0.008473476899985144
Median: 0.008239049499934481

---
Times for *Failure* **with** trace:
```text
0.013420927999959531
0.012825421999878017
0.011001540000052046
0.010464770999988104
0.010328669999807971
0.010199214000067514
0.010159646000147404
0.010200638000014806
0.010227348999933383
0.010360593999848788
```
Average: 0.010918877199969756
Median: 0.01034463199982838

---

Average difference: -0.002445400299984612
Median difference: -0.002105582499893899

*Obs.: **WITHOUT - WITH***

**Comment by sobolevn** [comment]
Thanks a lot for your amazing work! 

20% overhead, but in absolute numbers - not so bad. Can we also measure memory consumption?

**Comment by thepabloaguilar** [comment]
Sure!! I'll use [memory-profiler](https://pypi.org/project/memory-profiler/) lib to measure the memory, or you have a better option to use?

**Comment by thepabloaguilar** [comment]
Code used to tests:
```python
if __name__ == '__main__':
    import timeit

    from memory_profiler import memory_usage

    mem = memory_usage(
        lambda: timeit.repeat("Failure('inner_value')", repeat=10, number=100000, globals=globals())
    )
    print(mem)
```
Executed command:
```sh
mprof run --python returns/result.py
```

---

Memory for *Failure* **without** trace:
![Memory for Failure without trace](https://user-images.githubusercontent.com/25423500/84228266-f3423f00-aabc-11ea-96eb-31b647597cbb.png)

```text
15.546875 MiB
15.6171875 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
15.6328125 MiB
```
Average: 15.623579545454545 MiB
Median: 15.6328125 MiB

---

Memory for *Failure* **with** trace:
![Memory for Failure with trace](https://user-images.githubusercontent.com/25423500/84228377-43b99c80-aabd-11ea-9767-7b72df29e700.png)

```text
15.609375 MiB
15.6875 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
15.6953125 MiB
```
Average: 15.6875 MiB
Median: 15.6953125 MiB

---

Average difference: -0.06392045454545503 MiB
Median difference: -0.0625 MiB

*PS: **WITHOUT - WITH***

**Comment by sobolevn** [comment]
Let's make this feature ready for production! Awesome works 🎉

**Comment by sobolevn** [comment]
> Without, Average: 0.008473476899985144
> With, Average: 7.410607238799992

That's 1000x slowdown! I guess, we should reconsider our API.
I though a bit about it, the only thing that comes to mind is explicit developer's decision about whetger or not traces are required.

I guess that we try something similar to:

```python
with collect_traces():
    ...
```

**Comment by thepabloaguilar** [comment]
Ok, but what `collect_traces` should do?

**Comment by sobolevn** [comment]
It should tell `Failure` to start collecting traces.

**Comment by thepabloaguilar** [comment]
I don't know other way than uses something in the system, but it's a bad thing because `Failure` won't be deterministic.

And, if we monkey patch `Failure`?
Adding a callable or boolean parameter to it, and inside `collect_traces` we mokey patch `Failure` with a partially applied that parameter.

```python
def Failure(inner_value, trace):
    ...

@contextmanager
def collect_traces():
    failure_with_trace = partial(Falilure, trace=[bool or a callable])
    # make monkey patch
```

**Comment by thepabloaguilar** [comment]
My intention to use a `callable` is to invert the control and give to the user another trace option with a custom function.

**Comment by sobolevn** [comment]
This is a hard thing to say, but! I like the monkeeypatch solution 😆

**Comment by thepabloaguilar** [comment]
I have made a prototype:
**example.py**
```python
import inspect
from contextlib import contextmanager
from typing import Any
from example_two import imported_function

from returns.result import Failure, _Failure


@contextmanager
def collect_traces():
    def new(self):
        stack = inspect.stack()
        return stack[2:]

    unpatched_init = getattr(_Failure, "_get_trace")
    setattr(_Failure, "_get_trace", new)
    try:
        yield getattr(_Failure, "_get_trace")
    finally:
        setattr(_Failure, "_get_trace", unpatched_init)


def my_func_one() -> Any:
    before_patch = Failure("Here!")
    with collect_traces():
        on_patching = Failure("Here!")
        on_patching_outer_function = my_func_two()
        on_patching_imported_function = imported_function()
    after_patching = Failure("Here!")
    after_patching_imported_function = imported_function()
    return (
        before_patch,
        on_patching,
        on_patching_outer_function,
        on_patching_imported_function,
        after_patching,
        after_patching_imported_function,
    )


def my_func_two() -> Any:
    return Failure("Here!")


if __name__ == "__main__":
    (
        before_patch,
        on_patching,
        on_patching_outer_function,
        on_patching_imported_function,
        after_patching,
        after_patching_imported_function,
    ) = my_func_one()

    print("================= BEFORE PATCH =================")
    before_patch.trace
    print("================= ON PATCHING =================")
    on_patching.trace
    print("================= ON PATCHING OUTER FUNCTION =================")
    on_patching_outer_function.trace
    print("================= ON PATCHING IMPORTED FUNCTION =================")
    on_patching_imported_function.trace
    print("================= AFTER PATCH =================")
    after_patching.trace
    print("================= AFTER PATCH IMPORTED FUNCTION =================")
    after_patching_imported_function.trace
```

**example_two.py**
```python
from returns.result import Failure


def imported_function():
    return Failure("Imported Failure")
```

**result.py**
```python
class _Failure(...):
    # CODE
    @property
    def trace(self) -> None:
        if self._trace:
            for frame in self._trace:
                print(f"{frame.filename}:{frame.lineno} in `{frame.function}`")
        else:
            print("NO TRACE")
```
*PS: I've made in this way just for test porpoise*

The output was:
```sh
================= BEFORE PATCH =================
NO TRACE
================= ON PATCHING =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/example.py:26 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:53 in `<module>`
================= ON PATCHING OUTER FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/example.py:42 in `my_func_two`
/home/pabloaguilar/Projects/returns/example.py:27 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:53 in `<module>`
================= ON PATCHING IMPORTED FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/example_two.py:5 in `imported_function`
/home/pabloaguilar/Projects/returns/example.py:28 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:53 in `<module>`
================= AFTER PATCH =================
NO TRACE
================= AFTER PATCH IMPORTED FUNCTION =================
NO TRACE
```

**Comment by thepabloaguilar** [comment]
What do you think??

**Comment by sobolevn** [comment]
This looks great! Do `IOFailure` and `FutureResult` work correctly with `collect_trace`?

**Comment by thepabloaguilar** [comment]
They should do! I've added the `_get_trace` method and modify `__init__` from the `_Failure` class, so if we add this method to those classes they'll work correctly. I'll make the same test as above to post the results here, as well.

```python
class _Failure(...):
    def __init__(inner_value: _ErrorType) -> None:
        super().__init__(inner_value, self._get_trace())

    def _get_trace(self):
        pass
```

Or we can add that method to the `BaseContainer` class, we'll just need to modify the `__init__` of `_Failure`, `_IOFailure` classes. `FutureResult` uses `Result` and `IOResult` internally, so it has to work properly.

**Comment by thepabloaguilar** [comment]
Oh, I didn't pay attention that `IOResult` uses `Failure` internally hahaha
I've made the same test as above with `IOResult` and `IOFailure`, the results are bellow:

**IOResult.from_failure**
```sh
================= BEFORE PATCH =================
NO TRACE
================= ON PATCHING =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/returns/io.py:689 in `from_failure`
/home/pabloaguilar/Projects/returns/example.py:28 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= ON PATCHING OUTER FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/returns/io.py:689 in `from_failure`
/home/pabloaguilar/Projects/returns/example.py:44 in `my_func_two`
/home/pabloaguilar/Projects/returns/example.py:29 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= ON PATCHING IMPORTED FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/returns/io.py:689 in `from_failure`
/home/pabloaguilar/Projects/returns/example_two.py:6 in `imported_function`
/home/pabloaguilar/Projects/returns/example.py:30 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= AFTER PATCH =================
NO TRACE
================= AFTER PATCH IMPORTED FUNCTION =================
NO TRACE
```

**IOFailure**
```sh
================= BEFORE PATCH =================
NO TRACE
================= ON PATCHING =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/example.py:28 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= ON PATCHING OUTER FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/example.py:44 in `my_func_two`
/home/pabloaguilar/Projects/returns/example.py:29 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= ON PATCHING IMPORTED FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/io.py:837 in `IOFailure`
/home/pabloaguilar/Projects/returns/example_two.py:6 in `imported_function`
/home/pabloaguilar/Projects/returns/example.py:30 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:55 in `<module>`
================= AFTER PATCH =================
NO TRACE
================= AFTER PATCH IMPORTED FUNCTION =================
NO TRACE
```

**FutureResult.from_failure**
```sh
================= BEFORE PATCH =================
NO TRACE
================= ON PATCHING =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/future.py:1323 in `from_failure`
/home/pabloaguilar/Projects/returns/example.py:31 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:58 in `<module>`
================= ON PATCHING OUTER FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/future.py:1323 in `from_failure`
/home/pabloaguilar/Projects/returns/example.py:47 in `my_func_two`
/home/pabloaguilar/Projects/returns/example.py:32 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:58 in `<module>`
================= ON PATCHING IMPORTED FUNCTION =================
/home/pabloaguilar/Projects/returns/returns/result.py:529 in `Failure`
/home/pabloaguilar/Projects/returns/returns/future.py:1323 in `from_failure`
/home/pabloaguilar/Projects/returns/example_two.py:7 in `imported_function`
/home/pabloaguilar/Projects/returns/example.py:33 in `my_func_one`
/home/pabloaguilar/Projects/returns/example.py:58 in `<module>`
================= AFTER PATCH =================
NO TRACE
================= AFTER PATCH IMPORTED FUNCTION =================
NO TRACE
```
*PS: The tests with `FutureResult` was basically call `FutureResult.from_failure("Here!").awaitable` a pass it to `anyio.run(...)` on function return!*

---

To get the **trace** value correctly from `IOResult` I've added a property:
```python
class IOResult(...):
    @property
    def trace(self) -> None:
        self._inner_value.trace
```

**Comment by sobolevn** [comment]
Now this looks like it can be implemented in its final form! @thepabloaguilar thanks a lot for your amazing research work!

**Comment by thepabloaguilar** [comment]
It was a great discussion!
I'll open the PR ASAP
