### ISSUE TITLE
Consider adding Trampolines support

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#413]
https://eli.thegreenplace.net/2017/on-recursion-continuations-and-trampolines/

**Comment by sobolevn** [comment]
https://github.com/kachayev/fn.py#trampolines-decorator

**Comment by sobolevn** [comment]
http://blog.higher-order.com/assets/trampolines.pdf

**Comment by thepabloaguilar** [comment]
I think this is a really interesting feature, I'd love to work on.
But, is `returns` the right place to create it? Or should we create another lib to put these "specific" things?

**Comment by sobolevn** [comment]
@thepabloaguilar it depends on the implementation.

Things to consider:
- We use `RequiresContext` that is not recursion safe
- Trampolines can emulate recursion with safety
- Can we use Trampolines to implement safe `RequiresContext`?

If we can, than Trampolines are going to be a primitive inside `returns`, if not and it has a lot of code - we can always move it to `trampolines` project: https://pypi.org/project/trampolines/ it is available on PyPI! 

So, a research is required 👍

**Comment by thepabloaguilar** [comment]
Can you tell me where `RequiresContext` is not recursion safe, please?? I'm not finding where recursion occurs 😞 

> if not and it has a lot of code

The Trampoline implementation does not have a lot of code, it's simple, but maybe we need to write a plugin code for it!

But, I think we can use Trampolines to implement safe recursion on `RequiresContext`, my point was:
If someone is interested to use only `trampolines`, it'll have to install `returns` to use only ~1%! All other things in `returns` are related to its containers, `trampolines` will be a non related feature like `curry` 🤔

**Comment by sobolevn** [comment]
> Can you tell me where RequiresContext is not recursion safe, please?

Any method like `.map`, `.bind`, `.ask`, etc: https://github.com/dry-python/returns/blob/master/returns/context/requires_context.py#L149

Try this:

```python
import sys
from returns.context import RequiresContext

r = RequiresContext.from_value(1)
for i in range(sys.getrecursionlimit() + 1):
    r = r.map(abs)

print(r(...))
# RecursionError: maximum recursion depth exceeded while calling a Python object
```

> it'll have to install returns to use only ~1%

That's not a bad thing! Because it does not have any resource-overhead for users of only a small part of the lib.

> trampolines will be a non related feature like curry

And that's fine too! Especially if you need a `mypy` plugin for it.

**Comment by thepabloaguilar** [comment]
Ok, I was thinking about here that we can not use the `Trampolines` itself to make `RequiresContext` recursion safe!
But we can use the idea, using iterations instead of recursion. Maybe it's possible.

What's the main reason to use `recursion`?? Because sometimes is easier to design our solution instead of using a loop (for, while)

What's the `Trampolines` idea?? Allow us to write recursively solutions without recursion limit (at least in languages that doesn't support tail recursion optimization natively)

How does `Trampolines` do that?? By providing an external loop for us, who calls the functions is the trampoline implementation. We just need to return the next function to be called!

Let me try explain why I think we can't use `Trampolines` in `RequiresContext`.

The `Trampolines` lifecycle is something like this:
1. Call the function
2. Verify if the returned value is a callable
3. If it's, then go back to step 1
4. If it isn't, return the value

The important information here is that we always have the values computed in step `2`, in the first iteration (or in `RequiresContext` the first function, the most inner function) we don't depend of any future argument. That's different from `RequiresContext`, we can't call the first function because we depends of the `deps` value, it's a future value the user'll pass and 'cause this we have `lambda deps: function(self(deps))`

Maybe this explanation is a bit confusing, let me know if you don't understand!

The option to be recursion safe is, instead of using recursion we can store all the functions and when the users call `context` we just use something like reduce, like in the example below:
```python
>>> import sys
>>> from functools import reduce

>>> functions = [(lambda x: x + 1) for _ in range(sys.getrecursionlimit() + 1)]
>>> reduce(lambda number, func: func(number), functions, 0)
1001
```

**Comment by sobolevn** [comment]
> Maybe this explanation is a bit confusing

No, it is clear to me! Thanks a lot!

> The option to be recursion safe is, instead of using recursion we can store all the functions and when the users call context we just use something like reduce, like in the example below

This looks like a valid idea to try. Will you? 🙏

**Comment by thepabloaguilar** [comment]
> This looks like a valid idea to try. Will you? 🙏

Yep, it'll be fun to try. I'll start to work on this issue on March 4 probably!

**Comment by thepabloaguilar** [comment]
I want to discuss the solution design of this feature `Trampolines` (i'll open another issue for the `RequiresContext`), I see to major design options:

1. The first one is the design from the example you sent, [fn.py (recur.tco)](https://github.com/kachayev/fn.py/blob/master/fn/recur.py):
```python
@recur.tco
def fact(n, acc=1):
    if n == 0: return False, acc
    return True, (n-1, acc*n)
```

Where the users return the arguments to call the function and possibly they can return a new function to be called! You can see that behavior in this extracted piece from [fn.py](https://github.com/kachayev/fn.py#trampolines-decorator):

> @recur.tco is a decorator that execute your function in while loop and check output:
> - (False, result) means that we finished
> - (True, args, kwargs) means that we need to call function again with other arguments
> - (func, args, kwargs) to switch function to be executed inside while loop

2. Or we can take another approach from the JS example:
```javascript
// Trampoline implementation
const trampoline = fn => (...args) => {
  let result = fn(...args)
  while (typeof result === 'function') {
    result = result()
  }
  return result
}

// Function to be use with trampoline
const sumBelowRec = (number, sum = 0) => (
  number === 0
    ? sum
    : () => sumBelowRec(number - 1, sum + number)
)

// Trampoline usage
const sumBelow = trampoline(sumBelowRec)
sumBelow(100000)
// returns 5000050000 🎉🎉🎉
```
Extracted from [Using trampolines to manage large recursive loops in JavaScript](https://blog.logrocket.com/using-trampolines-to-manage-large-recursive-loops-in-javascript-d8c9db095ae3/)

---

In my opinion, the approach from `fn.py` will be more familiar to the Python users but seems magical how the trampolined function is called under the hoods, while the JS approach seems more clear by forcing the users to write the desired function call!

I'm just showing the possible options, my vote is for the first approach! If you have other designs in mind, please share.

**Comment by sobolevn** [comment]
Which one is easier to type-check?

**Comment by thepabloaguilar** [comment]
I think the second approach will be easier since we'll have just two return type `Callable[..., ...]` and the final result type:

```python
_TRT = NewType('_TRT')
_RT = Union[Callable[[], _TRT], _TRT]

def trampoline(func: Callable[..., _RT]) -> Callable[..., _TRT]:
    def trampolined(*args: Any, *kwargs: Any) -> _TRT:
        result = func(*args, **kwargs)
        while callable(result):
            result = result()
        return result
    return trampolined

def sum_below_rec(number: int, sum: int = 0) -> Union[Callable[[], int], int]:
    if number == 0:
        return sum
    return lambda: sum_below_rec(number - 1, sum + numer)

sum_below = trampoline(sum_below_rec)
print(sum_below(100000))
```

_Disclaimer: I didn't test the above code yet_

**Comment by thepabloaguilar** [comment]
Well, now I prefer the first approach 'cause I'm afraid the amount of `Any`s hahaha
Will be great if you already have `ParamSpec` 😞

**Comment by sobolevn** [comment]
Thanks a lot! Great research! 👍 

Can we remove `Any` from `_RT = Union[tuple[bool, _TRT], tuple[bool, Any, Any], tuple[Callable[..., _TRT], Any, Any]]`?
Because I want trampolines to be designed as safe as actual function calls.

**Comment by thepabloaguilar** [comment]
For now, we can't remove (I think). Those `Any` represent the arguments to the function that will be called under the hoods!
If we have `ParamSpec` we can easily remove those!

Btw, I've just edited my second comment above! The first example is about second approach (JS like) and the second example is about the first approach (decorator) hahaha

**Comment by sobolevn** [comment]
@thepabloaguilar is it doable with a plugin?

**Comment by thepabloaguilar** [comment]
Hummm maybe not, I think we don't have the necessary information! we have? 🤔

**Comment by thepabloaguilar** [comment]
Maybe we can do some work, the decorator solution will be something like this using `ParamSpec`!!

```python
P = ParamSpec("P")
NewP = ParamSpec("NewP")

_ReturnType = TypeVar('_ReturnType')

# Use as a decorator
def trampoline(
    func: Callable[
        P, 
        Union[
            tuple[Literal[True], _ReturnType],
            tuple[Literal[False], P.args, P.kwargs],
            tuple[Callable[NewP, _ReturnType], NewP.args, NewP.kwargs],
        ],
    ]
) -> Callable[..., _ReturnType]:
    def trampolined(*args: P.args, *kwargs: P.kwargs) -> _TRT:
        ...
    return trampolined
```

I'll try to take a look in our plugin today, I think we can emulate using the same mechanics of `curry`

**Comment by thepabloaguilar** [comment]
A few news about this here, I was making my presentation about `Trampolines` and just realized that we can't use the approach from this comment: https://github.com/dry-python/returns/issues/413#issuecomment-804237101

__mypy doesn't support recursive type annotations!!__

The solution we should follow is that from my last comment here (https://github.com/dry-python/returns/issues/413#issuecomment-804929515), we just need to wait the `ParamSpec` evaluation from `mypy`

**Comment by sobolevn** [comment]
@thepabloaguilar there's a hack we can use:

```python

from __future__ import annotations

from typing import Union, Protocol, Type, TYPE_CHECKING

if TYPE_CHECKING:
    class JSONArray(list[JSON], Protocol):  # type: ignore
        __class__: Type[list[JSON]]  # type: ignore

    class JSONObject(dict[str, JSON], Protocol):  # type: ignore
        __class__: Type[dict[str, JSON]]  # type: ignore

    JSON = Union[None, float, str, JSONArray, JSONObject]
```

**Comment by thepabloaguilar** [comment]
So, the transformation of this:
```python
_ReturnType = TypeVar('_ReturnType')
_TrampolineFunc = Callable[
    [],
    Union['_TrampolineFunc', _ReturnType],
]
```

Is kind of this:
```python
class TrampolineFuncReturn(Protocol[_ReturnType]):
    __class__: Type[Union['_TrampolineFunc', '_ReturnType']]

_ReturnType = TypeVar('_ReturnType')
_TrampolineFunc = Callable[
    [],
    TrampolineFuncReturn,
]
```
> I got a mypy error on `__class__`

**Comment by sobolevn** [comment]
I had some time to work on this:

```python
from typing import Callable, ParamSpec, TypeVar, Generic

R = TypeVar('R')
P = ParamSpec('P')

class Trampoline(Generic[R]):
    def __init__(self, func: Callable[P, R], /, *args: P.args, **kwargs: P.kwargs) -> None:
        self.func = func
        self.args = args
        self.kwargs = kwargs

    def __call__(self) -> R:
        return self.func(*self.args, **self.kwargs)

def trampoline(func: Callable[P, R | Trampoline[R]]) -> Callable[P, R]:
    def decorator(*args: P.args, **kwargs: P.kwargs):
        trampoline_result = func(*args, **kwargs)
        while isinstance(trampoline_result, Trampoline):
            trampoline_result = trampoline_result()
        return trampoline_result
    return decorator

from typing import Iterator

@trampoline
def accumulate(origin: Iterator[int], acc: int = 0) -> int | Trampoline[int]:
    n = next(origin, None)
    if n is None:
        return acc
    return Trampoline(accumulate, origin, acc + n)

res: int = accumulate(iter([1, 2, 3]))
print(res)  # 6

```

It works 🎉 

I mean that both `mypy` and `python` are happy with it.
