### ISSUE TITLE
Add a helper to test traces

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#430]
We should add a new method to `pytest` plugin. We need to test traces.

Here's the usecase we are trying to cover. Imagine, there are multiple places where `Failure` can happen with the same result. For example:

```python
def first() -> ResultE[int]:
    return Failure(KeyError('a'))

def second() -> ResultE[int]:
    return Failure(KeyError('a'))
```

And we need to test that the reason why our app failed is `first()` call, not `second()` 
Matching by value is not good enough here, since values are identical. But, we can use traces!

```python
def test_failure(returns):
    assert returns.has_trace(my_function(), 'some trace object with `first()` call')
```

And it will pass for `Failure` created by `first()` and fail for `Failure` created by `second()`

Related to #409 
CC @thepabloaguilar

**Comment by thepabloaguilar** [comment]
I have an initial idea! In one of my researches for #409 I thought in use `sys.settrace(...)`.
We can start some tests with it.
But we'll have problems with [coveragepy](https://github.com/nedbat/coveragepy) because it uses `settrace`, I think we cannot have multiples tracers.

* [Python sys.settrace reference](https://docs.python.org/3/library/sys.html#sys.settrace)
* [Geeek for Geeks example](https://www.geeksforgeeks.org/python-sys-settrace/)
* [PyMOTW example](https://pymotw.com/2/sys/tracing.html)

Possibly problems with *coveragepy*:
* [Things that don’t work](https://coverage.readthedocs.io/en/coverage-5.1/trouble.html#things-that-don-t-work)
* https://github.com/nedbat/coveragepy/issues/683

**Comment by thepabloaguilar** [comment]
We can make something like:

```python
import sys

@curry
def my_trace_func(func: Callable[..., ...], ...):
    func(...)  # we repass the trace arguments to the old function
    # Our trace code here

sys.settrace(my_trace_func(sys.gettrace())
```

**Comment by sobolevn** [comment]
Thanks a lot for the great links! I was not aware of `coverage` problem. 

I don't really care about the internal architecture of the plugin hook. It should *just work*. Since, it is a developer utility we can do as much magic as needed. But, I would recommend to use `partial` instead of `curry` when possible, because it is much faster. (Btw, this can go to the docs on its own)

PRs are welcome! I am currently working on HKT support almost full-time.

**Comment by thepabloaguilar** [comment]
So, we can use `settrace` without most effort! Your recommended API is great, but what about change the second argument to use the `function` reference instead a string?
```python
def first() -> ResultE[int]:
    return Failure(KeyError('a'))

def second() -> ResultE[int]:
    return Failure(KeyError('a'))

def test_failure(returns):
    assert returns.has_trace(my_function(), first)
```

I think it's easier to implement using the function reference than pass a string, think in a scenario where we have more than one function with the same name! Passing the reference we just have to do `wanted_function is function`.

**Comment by thepabloaguilar** [comment]
I'll make a prototype asap!

**Comment by sobolevn** [comment]
@thepabloaguilar sure, I used `str` because I was not sure what to put there. 🙂

**Comment by thepabloaguilar** [comment]
I've made a prototype!
```python
class _ReturnsAsserts(object):
    def has_trace(self, function_to_call, function_reference) -> bool:
        def trace_func(function_to_search, frame, event, arg) -> None:
            if event == 'call':
                if getattr(function_to_search, '__code__', None) is frame.f_code:
                    raise FunctionFoundWhileTracing()

        try:
            old_tracer = sys.gettrace()
            sys.settrace(partial(trace_func, function_reference))
            function_to_call()
        except FunctionFoundWhileTracing:
            return True
        finally:
            sys.settrace(old_tracer)
        return False
```

I've validated with these tests:
```python
def other_function():
    pass

def test_trace_one(returns): # This test passed, the `other_function` call was identified
    def my_func():
        other_function()
    assert returns.has_trace(my_func, other_function)

def test_trace_two(returns):  # This test didn't pass, `my_func` never calls `other_function`
    def my_func():
        pass
    assert returns.has_trace(my_func, other_function)
```

---

I didn't want to raise an exception to tell when function is called, but trace_function can't return any value to us and I think that isn't good idea make `trace_func` modify a variable out of it context!

**Comment by thepabloaguilar** [comment]
I think it's the better way to implements that helper!
But one thing we have to consider is that your initial idea is to trace where the `Failure` was created, the above prototype will work for *"everything"*. If we'll restrict just for `Failure` the implementation should be:

```python
class _ReturnsAsserts(object):
    def has_trace(self, function_to_call, function_reference) -> bool:
        # Function to `sys.settrace`
        def trace_func(function_to_search, frame, event, arg) -> None:
            # Verify if it's a 'call' event and this call is to the `Failure` function
            if event == 'call' and frame.f_code is Failure.__code__:
                current_call_stack = inspect.stack()
                function_code = getattr(function_to_search, '__code__', None)
                # Traverse the call stack searching for expected function
                for frame_ in current_call_stack:
                    if function_code is frame_.f_code:
                        raise FunctionFoundWhileTracing()

        try:
            old_tracer = sys.gettrace()
            sys.settrace(partial(trace_func, function_reference))
            function_to_call()
        except FunctionFoundWhileTracing:
            return True
        finally:
            sys.settrace(old_tracer)
        return False
```

What you think?

**Comment by thepabloaguilar** [comment]
@sobolevn I'll proceed with this implementation, do you have any comments?

**Comment by sobolevn** [comment]
LGTM! 👍 

Thanks a lot!

**Comment by thepabloaguilar** [comment]
I'm implementing and I've decided to change a bit the API. It will be like `pytest.raises`:
```python
def test_something(returns) -> None:
    with returns.has_trace(Success, function_foo):
        function_bar()
```
