### ISSUE TITLE
creating unit Result.Failure object from an Exception should provide traceback, chaining

### ISSUE THREAD

**Issue by robfitzgerald** [dry-python/returns#436]
in the below code, the method `resolve_my_workflow` uses a hack to artificially raise an exception in order to capture the stack trace details. however, the source of the failure, due to `likes_positive_numbers`, fails to provide it's line number and context. one solution would require adding these try/except hacks to every function in the workflow, which adds a large amount of boilerplate and also would seem to be contrary to the objective of separation of concerns here (not to mention, get messy quick).

could such a Failure constructor or annotation provide the boilerplate handling of making `Result`s capable of exception chaining without requiring **returns** users to create try/catch blocks?

```python
from returns.primitives.exceptions import UnwrapFailedError
from returns.result import ResultE, Success, Failure
from returns.pointfree import bind
from returns.pipeline import flow


def likes_positive_numbers(n: int) -> ResultE[str]:
    if n < 0:
        return Failure(ArithmeticError(f"n ({n}) is less than 0"))
    else:
        return Success(f"happy happy joy joy |" * n)


def likes_even_length_strings_that_are_short(s: str) -> ResultE[bool]:
    if len(s) % 2 != 0:
        return Failure(ValueError(f"I don't like uneven strings but you gave me one with {len(s)} characters dude"))
    else:
        return Success(len(s) < 100)


class WorkflowException(Exception):
    def __init__(self, expression, message):
        self.expression = expression
        self.message = message


def resolve_my_workflow(r: ResultE[bool]) -> ResultE[str]:
    try:
        return Success(f"result is good: {r.unwrap()}")
    except UnwrapFailedError:
        try:
            raise WorkflowException("test n is positive, even and short", "workflow failed on input") from r.failure()
        except WorkflowException as w:
            return Failure(w)


if __name__ == "__main__":

    def my_workflow(n: int) -> ResultE[str]:
        """
        takes a number, tests if it is 0 or greater, even, and less than 100 characters
        :param n: the input number
        :return: either a Success[str] or a Failure[Exception]
        """
        return flow(
            n,
            likes_positive_numbers,
            bind(likes_even_length_strings_that_are_short),
            resolve_my_workflow
        )

    experiments = [  # examples which illustrate different Results with exception chaining
        (1, my_workflow(1)),    # fails with ValueError > WorkflowException chain
        # (-1, my_workflow(-1)),  # fails with ArithmeticError > WorkflowException chain
        # (2, my_workflow(2)),    # success
    ]

    # the outer scope where we finally deal with exceptions
    for e in experiments:
        test, result = e
        try:
            print(f"{test} : {result.unwrap()}")
        except UnwrapFailedError as e:
            failure = result.failure()
            raise failure
```

console:

```
ValueError: I don't like uneven strings but you gave me one with 21 characters dude

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rfitzger/dev/nrel/hive/hive/hive/returns_exception_chaining.py", line 68, in <module>
    raise failure
  File "/Users/rfitzger/dev/nrel/hive/hive/hive/returns_exception_chaining.py", line 32, in resolve_my_workflow
    raise WorkflowException("test n is positive, even and short", "workflow failed on input") from r.failure()
__main__.WorkflowException: ('test n is positive, even and short', 'workflow failed on input')
```

**Comment by thepabloaguilar** [comment]
Hello @robfitzgerald!
`returns` provides a development tool to [Trace Failures](https://returns.readthedocs.io/en/latest/pages/development.html#tracing-failures), it's not released yet but you can try from the `master` branch source code! It's not thread safe, just use it to develop only.

A brief explanation of what `Result.Failure` doesn't have to provide a traceback when it's internal value is an Exception:
> An Exception by itself doesn't provide a traceback, a traceback is a result of `raise` keyword combined with an Exception. The operation to get that traceback is heavy, we can't do this because all of `returns`' users will be affected by this unnecessary overhead on their systems.

If you want, you can use `inspect` built-in lib, and create your custom Exception class:
```python
import inspect

class ExceptionWithTraceback(Exception):
    def __init__(self, message):
        super().__init__(message)
        self.traceback = inspect.stack()
```
Btw, we use `inspect` internally in `@collect_traces`

Your function should be something like:
```python
def resolve_my_workflow(result: ResultE[bool]) -> ResultE[str]:
    return result \
        .map(lambda inner_value: f"result is good: {inner_value}") \
        .alt(lambda __: ExceptionWithTraceback("test n is positive, even and short workflow failed on input"))
```

**Comment by robfitzgerald** [comment]
ok, great! thank you for the quick reply. this is what i was looking for. i agree, it's great to have this only activated by something like a DEV environment variable. i'm coming from Scala and so the added trace cost in Python is not obvious to me.

if it's helpful to mention, i didn't find Trace Failures because i was looking for it in the `Return` documentation itself.

thank you for your work on this project!

**Comment by thepabloaguilar** [comment]
> ... i'm coming from Scala and so the added trace cost in Python is not obvious to me.

R: We have some statistics [here](https://github.com/dry-python/returns/issues/409#issuecomment-642142393) about the overhead to get the entire call stack everytime that a `Failure` is created.

---

> if it's helpful to mention, i didn't find Trace Failures because i was looking for it in the `Return` documentation itself.

R: It's because `@collect_traces` works with `IOResult` and `FutureResult`, as well!
