### ISSUE TITLE
Example error in `Result` container section

### ISSUE THREAD

**Issue by thepabloaguilar** [dry-python/returns#454]
We have this example in "[How to compose error types?](https://returns.readthedocs.io/en/latest/pages/result.html#how-to-compose-error-types)" section:

```python
>>> from returns.result import Result, Success

>>> def div(number: int) -> Result[float, ZeroDivisionError]:
...     return Success(1 / number)

>>> container: Result[int, ValueError] = Success(1)
>>> str(container.unify(div))
'<Success: 1.0>'

>>> # => Revealed type is:
>>> # Result[float, Union[ValueError, ZeroDivisionError]]
```

`div` function is not safe if we pass `0 (zero)` as an argument!
I know that example is about `unify` method, but we can make a little improvement there, maybe:
```python
def div(number: int) -> Result[float, ZeroDivisionError]:
    if number:
        return Success(1 / number)
    return Failure(ZeroDivisionError('division by zero'))
```

I'm opening this issue because a friend of mine had some questions around `div`.

**Comment by sobolevn** [comment]
Yes, this is a bug. Can you please send a fix?

**Comment by thepabloaguilar** [comment]
@kenjihiraoka, you've found this bug, feel free to fix it!
It's a great issue to begin in an `Open Source` world.

**Comment by sobolevn** [comment]
I would love to help @kenjihiraoka if anything is needed! 👍

**Comment by kenjihiraoka** [comment]
Thanks @sobolevn, I already open the pull request :smile:
