### ISSUE TITLE
Test monad laws with a custom pytest plugin

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#457]
1. https://arrow-kt.io/docs/0.10/arrow/typeclasses/monad/#laws
2. https://github.com/arrow-kt/arrow-core/blob/master/arrow-core/arrow-test/src/main/kotlin/arrow/test/laws/MonadLaws.kt

**Comment by thepabloaguilar** [comment]
[Verifying Typeclass Laws in Haskell with QuickCheck](https://austinrochford.com/posts/2014-05-27-quickcheck-laws.html)

**Comment by sobolevn** [comment]
Or, we can use data-types to represent different `Laws`: https://github.com/zio/zio/blob/f963adee37635f021a741d9d5ae4ca2ed4890b10/test/shared/src/main/scala/zio/test/laws/ZLawful.scala

For example:

```python
class Functor(Law[Laws.Identity], ...): ...
```

It looks like something I really want to research.

**Comment by sobolevn** [comment]
Also:
- https://github.com/zio/zio/blob/f36ba93af21f4cdcd880a39bde7911f127ff1fc6/test/shared/src/main/scala/zio/test/laws/package.scala
- https://github.com/zio/zio/blob/f963adee37635f021a741d9d5ae4ca2ed4890b10/test-tests/shared/src/test/scala/zio/test/laws/LawsSpec.scala

This is super cool idea!

We can also add `hypothesis` as `returns[test]` dependency and use API like `returns.check_laws(my_custom_container)` in tests to test the hell out of it.

**Comment by sobolevn** [comment]
Done in #533
