### ISSUE TITLE
Consider renaming `.failure()`

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#460]
Currently, it does not make much sense in `Unwrappable` interface. Because it can represent not just a failure, but anything else.

`.unwrap()` is a pretty generic name, but `.failure()` is to specific to `Result`.

**Comment by sobolevn** [comment]
I don't like `left` and `right`. Moreover, we have `left` as a `success` and `right` as a `failure`. Which is not common.

Some ideas:
- `.other()`
- `.unwrap_other()`
- `.unwrap2()`
- `.alternative()`
- `.unwrap_alt()`
- `.alt_unwrap()`
- `.unfold()`

**Comment by thepabloaguilar** [comment]
It's little hard to think about. I have suggestion too:

* `.second()`

Because we have `{Mappable, Bindable, Applicative}N`:
```python
class Example(MappableN[_FirstType, _SecondType, _ThirdType]):
    ...
```

`.second()` and `.third()` sounds great with this example.

**Comment by sobolevn** [comment]
What about renaming `.unwrap()` as well? It might be a good idea for consistency: `.first()` and `.second()`.

**Comment by thepabloaguilar** [comment]
And what about rename to:

* `.unwrap_first()`
* `.unwrap_second()`

It's more clear we're unwrapping something.

**Comment by sobolevn** [comment]
`.unwrap()` and `.unwrap_second()`?

**Comment by thepabloaguilar** [comment]
> `.unwrap()` and `.unwrap_second()`?

Following this idea, I have doubt between `.unwrap_second()` and `.unwrap_other()`! Both sounds great.

**Comment by thepabloaguilar** [comment]
I think `.unwrap()` & `.unwrap_other()` sounds more natural than `.unwrap()` & `unwrap_second()`!

**Comment by thepabloaguilar** [comment]
I would like to resolve this issue because this modification will impact many of our classes!

I think we have two options:
* `.unwrap()` & `.unwrap_second()`
* `.unwrap()` & `.unwrap_other()`

My vote is for `.unwrap()` & `.unwrap_other()`:
```python
result: Result[int, str] = Success(1)

# when we want to get the value or default we can do this
print(result.value_or(None)) # this sounds like `give me the value if it's a success or this OTHER value`

# following this idea it's more natural to read code like this
print(result.unwrap_other())
# than
print(result.unwrap_second())
```

**Comment by thepabloaguilar** [comment]
@sobolevn what do you think?

**Comment by sobolevn** [comment]
Sorry, didn't have the time to think about it yet.

**Comment by sobolevn** [comment]
Since `.failure()` now only lives in `ResultLikeN`, there's no need to rename it.
