### ISSUE TITLE
Mypy fails to infer return type of 'returns.pipeline.flow' with certain arguments

### ISSUE THREAD

**Issue by mysticfall** [dry-python/returns#476]
I wrote a simple utility module in [my project](https://github.com/mysticfall/alleycat-reactive), and when I run `mypy`(with `returns_plugin`) it fails to infer the return type of some of its functions using `returns.pipeline.flow`

The module in question is [utils.py](https://github.com/mysticfall/alleycat-reactive/blob/master/alleycat/reactive/utils.py), and as you see it I had to use various workarounds (e.g. `# type:ignore`, `inst: Instruction`) to circumvent the problem.

If you remove those workarounds and run `mypy`, you will see type related errors like these,
``` 
alleycat/reactive/utils.py:18: error: "List[Callable[[Maybe[FrameType]], Maybe[FrameType]]]" not callable
alleycat/reactive/utils.py:46: error: <nothing> has no attribute "argval"
```
I'm new to `returns`/`mypy` and also Python in general, so it's entirely possible that I'm maybe doing something in a wrong way. In that case, I'd appreciate if someone could direct me into the right direction.

Thanks!

**Comment by sobolevn** [comment]
Yes, this can be true. Why?
1. `lambda` functions. They are always typed as `Any => ...` It might be hard for `mypy` to infer them correctly
2. Builtin functions might have some invalid typing as well

What can be done?
In you particular case you can create fully typed `custom_dropwhile` that accepts arguments in a different way:

```python
flow(
            dis.get_instructions(frame.f_code),
            custom_dropwhile(lambda i: not i.opname.startswith("SETUP_ANNOTATIONS")),
```

You can also try https://github.com/dry-python/lambdas to see if it performs any better.

**Comment by mysticfall** [comment]
> 1. `lambda` functions. They are always typed as `Any => ...` It might be hard for `mypy` to infer them correctly
Coming from Scala background, this really surprised me. Even the fact that I have to always type `lambda` alone feels pretty awkward to me and now that I learned it also can't be typed properly... well.

> What can be done?
> You can also try https://github.com/dry-python/lambdas to see if it performs any better.

`lambdas` looks to be something I really need to ease myself into the Python world. Thanks much for the help, and also for creating all those projects to make life easier for people like me :)

**Comment by sobolevn** [comment]
Happy to help! 👍
