### ISSUE TITLE
Use `flow` with multiple parameters.

### ISSUE THREAD

**Issue by michaelbukachi** [dry-python/returns#509]
I can't seem to figure out how to use `flow` with a function that accepts multiple parameters. All examples in the documentation use functions with a single parameter. Here's a short snippet demonstrating what I'm trying to do:
```
from returns.pipeline import flow
def add(a, b):
...     return a + b
... 
assert flow(1, 2, add) == 3
```

**Comment by sobolevn** [comment]
I am afraid, that this won't work. You can try to use `@curry` to achieve that. But, it is currently broken: #462

**Comment by michaelbukachi** [comment]
Oh. Guess I have to rollback to use of `@pipeline`. Is there anybody looking into it? Might try to do a PR.

**Comment by sobolevn** [comment]
Do you mean looking into #462?

**Comment by michaelbukachi** [comment]
Yes.

**Comment by sobolevn** [comment]
I would appreciate your help! Thanks a lot!

Also, see https://github.com/python/mypy/issues/9147

**Comment by michaelbukachi** [comment]
Great. Thanks.

**Comment by michaelbukachi** [comment]
So the underlying bug is Mypy issue.So it would better to do a PR to mypy right?

**Comment by sobolevn** [comment]
Yes. There are two options:
- solve the issue correctly for nested `overloaded` by changing how compare works
- submit my hack with equality check

**Comment by sobolevn** [comment]
I am closing this one, let's coordinate in #462
