### ISSUE TITLE
Monad laws as values

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#533]
We need to add self-checkable monad laws represented as types.

Here are some context: 
- https://github.com/zio/zio/blob/f36ba93af21f4cdcd880a39bde7911f127ff1fc6/test/shared/src/main/scala/zio/test/laws/package.scala
- https://github.com/zio/zio/blob/f963adee37635f021a741d9d5ae4ca2ed4890b10/test-tests/shared/src/test/scala/zio/test/laws/LawsSpec.scala

Related: https://github.com/dry-python/returns/issues/457

Some very early prototype:

```python
class SymmetryLaw(Law, Generic[_E]):
    def statement(self, a: _E, b: _E) -> bool:
        return a == b is b == a

    def run(self) -> NoReturn:
        # TODO: hypothesis stuff
```

**Comment by sobolevn** [comment]
Oh fuck, this is hard!

**Comment by sobolevn** [comment]
After merging https://github.com/HypothesisWorks/hypothesis/pull/2550 this feature is unblocked. I can return to it.

**Comment by kyprifog** [comment]
Wow this would be awesome!
