### ISSUE TITLE
Consider adding popups for docs

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#537]
Like hypothesis has: https://hypothesis.readthedocs.io/en/latest/data.html
<img width="512" alt="Снимок экрана 2020-08-06 в 11 27 50" src="https://user-images.githubusercontent.com/4660275/89509400-f06f7c00-d7d7-11ea-8480-71da315466b8.png">

**Comment by thepabloaguilar** [comment]
Seems easy to use: [sphinx-hoverxref](https://sphinx-hoverxref.readthedocs.io/en/latest/)
What references do we have to put this?

**Comment by sobolevn** [comment]
> What references do we have to put this?

Sorry, I don't get your question. 🙂

**Comment by sobolevn** [comment]
Basically all refences like `:meth:`, `:class:`, `:func:`, etc
