### ISSUE TITLE
Real life examples

### ISSUE THREAD

**Issue by asyncee** [dry-python/returns#54]
Hello!

This library looks interesting as a "ROP" approach to exception handling. Can you provide more real-life examples with usage of `rescue` for example?

As i understand, currently `rescue` function is only usable for transforming exception message into some response, because when exception happens, `Failure` holds no context but exception instance.

My case:

```
task = get_next_task_from_db()

try:
    result = process_task(task)  # result is a dataclass with success: bool, payload: dict
except Exception as e:
    task.set_exception(e)
else:
    if result.success:
        task.set_complete(result.payload)
    else:
        task.set_failed(result.payload)

put_task_into_db(task)
```

I'm not sure of how to rewrite this code in a functional manner.

**Comment by sobolevn** [comment]
Hi, @asyncee! Thanks for raising this question.

The thing is: this code is 100% imperative. It is hard to rewrite it to functional version without big refactoring and deep understanding of the problem.

Straight forward approach:

```python
@safe
def process_task(...) -> Payload:
    ...

@pipeline
def your_function(task):
     process_task(task).rescue(
         lambda exc: task.set_exception(exc),
     ).bind(
         lambda result: task.set_complete(result.payload) if result.success else task.set_failed(result.payload),
     )
```

But, I do not like this code. And do not recommend to use it.
I would try to refactor `task.set_*` methods to `task.apply_result()` method.
And this way I can use it like so: `task.apply_result(result)`. And it is a matter of `result` to know its state.

I would love to hear your story! And would be happy to see your code.

**Comment by asyncee** [comment]
@sobolevn thanks for responding fast!

I totally agree with you that there are no benefit in the rewritten code example and my original code/architecture should be refactored for functional paradigm.

I think that functional programming can help with creating a fluid and readable interface, it would be cool to come up with something like this in the end (just a fictional example):

```
def create_prefs_if_not_exist(exception: Exception, result: User):
    # Result here is a value that was passed in previous step (update_user_preferences).
    # result allows to know execution context of a function on a previous stack level.
    if isinstance(exception, DoesNotExist):
            return create_prefs(result)
    return Failure(exception, result)

result = (
    load_user()  # load user from db
    # Do some validation. What should be a result of this function: Failure with descriptive message or Exception? Should validation return Failure(message) or raise an exception?
    .validate_user()
    .bind(update_user_preferences)  # update their prefs
    .rescue(create_prefs_if_not_exist)
)
return_http_response(result)   # return 200 OK or 4xx or 5xx, result is of type Result.
```

But i'm not sure if it can be implemented right now, because `rescue` function has no context (and also not a closure), so it is not aware of user returned from `load_user`.

Any way the point is to make code not only readable but more compact.

Just a thoughts :)

**Comment by sobolevn** [comment]
I like the second example! Looks awesome.
Btw, you can place anything into the `Failure`, not just exception. Or use `@pipeline` to have some context.
