### ISSUE TITLE
Enable RTD check in PRs

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#547]
See: https://readthedocs.org/projects/hypothesis/builds/11631177/

I would be awesome to have! Because sphinx break quite frequently.

**Comment by thepabloaguilar** [comment]
Just you can do this, it's pretty easy!!

[Autobuild Documentation for Pull Requests](https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html)

**Comment by sobolevn** [comment]
Thanks! Will do.

**Comment by thepabloaguilar** [comment]
Would be great to enable this check asap to prevent documentation fails from future PRs

**Comment by sobolevn** [comment]
I am on it!

**Comment by sobolevn** [comment]
Link https://returns--621.org.readthedocs.build/en/621/
