### ISSUE TITLE
Unwrapping failures erases exception type information

### ISSUE THREAD

**Issue by thedrow** [dry-python/returns#56]
Let's say I unwrap a failure and want to catch it using try-except.

The only way to do so currently is:
```python
from returns.result import Result
from returns.functions import safe
from returns.primitives.exceptions import UnwrapFailedError

@safe
def foo(i) -> Result[int, Exception]:
  if i == 0:
    raise ValueError("problem")
  return i + 5

try:
  result = foo('a') # Will raise TypeError
  # do stuff
  result.unwrap()
except UnwrapFailedError as e:
  try:
    raise e.halted_container.failure() from e
  except ValueError:
    print("Don't use zero")
  except TypeError:
    print("Dont use strings")
```
This makes exception handling code more complex than it should be.

Naturally you could have also used:
```python
@safe
def handle_err(e) -> Result[None, Exception]:
  if isinstance(e, ValueError):
    print("Don't use zero")
  elif isinstance(e, TypeError):
    print("Dont use strings")
  else:
    raise e from e

try:
  foo('a').rescue(handle_err).unwrap()
except UnwrapFailedError:
  print("Unhandled exception!!!")
```

But the error handling code above simply feels unpythonic and awkward.

Rescuing from an error fits the usecase where you want to log the error and proceed or any other generic error handling situation.

You could make `rescue()` accept a mapping between types to callables and call the appropriate error handler when an exception occured but I don't see why you'd have to do so.

It seems to me that the `UnwrapFailedError` exception is not necessary and hinders code readability.
The try-except clause was created for such situations. We should use it.

**Comment by sobolevn** [comment]
Hi, @thedrow! Thanks for your feedback.

But, I do not understand what exactly you are trying to achieve. 
> Let's say I unwrap a failure and want to catch it using try-except

But why do you want to do it? In case you need an exception you can do it like so:

```python
container: Failure[SomeException]
exc = container.failure()
```

But, I would like to remove `UnwrapFailedError` if you can provide a sample on how it is possible without internal exceptions.

**Comment by thedrow** [comment]
I'd like to use try-except because it's the only effective, clear and idiomatic way to handle different types of errors.

Your suggestion seems to involve checking if the `Result` is a `Failure`:

```python
if not is_successful(result):
  try:
     result.failure()
  except Whatever:
    pass
```

Which is also a dance I'd like to avoid.

I tried using a metaclass in order to pretend to be another exception but that doesn't work unfortunately.

```python
class ExcMeta(type):
    def __instancecheck__(cls, i):
        print(cls)
        print(i)
        return True
        
    def __subclasscheck__(cls, i):
        print(cls)
        print(i)
        return True

class Exc(Exception, metaclass=ExcMeta):
  pass

e = Exc("OMG")

try:
    raise e
except ValueError:
    print("Handled")
except Exc:
  print("Boo")
```

This program prints Boo.
If we can fool the exception matching mechanism to catch both the inner exception and the `UnwrapFailedError` that we'll have something we can use.

**Comment by sobolevn** [comment]
Will this sample work for you?

```python
from typing import NoReturn

from returns.result import Failure

def raise_(exception: Exception) -> NoReturn:
    raise exception

try:
    # Setting up imaginary instance:
    result = Failure(TypeError('my message'))
    # Raising actual exception:
    result.fix(raise_)
except ValueError as ex:
    print('value:', ex)
except TypeError as ex:
    print('type:', ex)
except Exception as ex:
    print('base:', ex)
# => type: my message

```

If so, we can make `raise_` function a part of our `functions.py` file.

**Comment by sobolevn** [comment]
Closed via https://github.com/dry-python/returns/pull/57

**Comment by thedrow** [comment]
Actually this isn't resolved since you still can't catch the original exception.

**Comment by thedrow** [comment]
It does provide more information and you can now do the following:
```python
try:
  result.unwrap()
except UnwrapFailedError as e:
  if isinstance(e.__cause__, ValueError):
   print('ValueError %s' % e)
```

This is better but still isn't the desired result.

What about adding an `unwrap_or_raise()` method which either unwraps the value or raises the original exception?

**Comment by sobolevn** [comment]
@thedrow I like `unwrap_or_raise()`!

**Comment by sobolevn** [comment]
So, @thedrow, if I understand you correctly we have to support the following case:

```python
result: Failure[ValueError]
result.unwrap()  # => fails with UnwrapFailedError(ValueError(...))
```

We need to actually raise the inner exception:

```python

# returns/functions.py
def raise_exception(exception: Exception) -> NoReturn:
    raise exception

# sample_code.py
from returns.functions import raise_exception

result: Failure[ValueError]
result.fix(raise_exception)  # => ValueError(...)

other_result: Failure[IndexError]
other_result.unwrap_or_raise()  # => IndexError(...)
```

What do you think about two ways of raising exceptions? Can we just stick to `fix(raise_exception)`?
Do we really need `unwrap_or_raise()`? 

I am opened to the suggestions.

**Comment by sobolevn** [comment]
inb4: I am not a big fan of rich API, since at some point it will look something like this: https://github.com/gcanti/fp-ts/blob/master/docs/modules/TaskEither.ts.md#taskeither-class

**Comment by thedrow** [comment]
I really don't mind having rich APIs as long as they are properly documented and tested.

**Comment by sobolevn** [comment]
Ok, so here's my proposal: the goal of this library is to use monads, not exceptions in the first place.
It should be really strange to add `unwrap_or_raise()` since it contradicts with the initial intention. 

As a result, we will stick to the `raise_exception` helper function and `fix()`. Here' how you can unwrap values the true way:

```python
result: Result[int, ZeroDivisionError]

# This only makes sense if you need this exception in your third-party API:
result.fix(raise_exception).unwrap()
```

**Comment by sobolevn** [comment]
Closed by https://github.com/dry-python/returns/commit/4e9ab7bd856b9af679a176df7a18b2f40d917dd4

**Comment by sobolevn** [comment]
Now it is `result.alt(raise_exception).unwrap()`
