### ISSUE TITLE
flatten on List[Maybe[T]]

### ISSUE THREAD

**Issue by kyprifog** [dry-python/returns#592]
Also asking if there is an existing way that i'm not seeing to do the following:

I expected:
```
flatten(List[Maybe[T]])
```
to return
```
List[T]
```
removing Nothing

**Comment by sobolevn** [comment]
Does this look like something similar to what you need? https://github.com/dry-python/returns/blob/master/returns/maybe.py#L281-L286

**Comment by kyprifog** [comment]
Doesn't that return a List[Maybe[T]]?  I'm looking for something that will take a List[Maybe[T]] and flatten it:
```
a: List[Maybe[int]] = [Nothing, Nothing, Maybe(3), Maybe (4)]
a: List[int] = flatten(a) == [3, 4]
```

**Comment by sobolevn** [comment]
You can pass `CollectAll` strategy there.

**Comment by sobolevn** [comment]
Let's move to #598

**Comment by kyprifog** [comment]
Sounds good that sounds much more robust.  I'll track the issue there
