### ISSUE TITLE
async/await support

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#60]
I guess we need to modify these lines:
- https://github.com/dry-python/returns/blob/master/returns/functions.py#L34
- https://github.com/dry-python/returns/blob/master/returns/functions.py#L49

And add `await` there. And it should be working.
I am also not sure about types and `.bind` methods that expects callables. Will it work with `asyncio`?

**Comment by sobolevn** [comment]
Origin: https://outcome.readthedocs.io

**Comment by vir-mir** [comment]
I think, should work if you add method `__await__`  in class  `Success`

**Comment by sobolevn** [comment]
@vir-mir yes, I agree. I do not want to make `Result` or any other containers awaitable. That's out of scope.

I want to make `@pipeline` and `@safe` decorators to work with `async def` functions. Do you want to help? 🙂

**Comment by thedrow** [comment]
It actually makes sense to make the result object awaitable. Maybe we can declare a special type of result: AsyncResult...

**Comment by sobolevn** [comment]
@thedrow I am not familiar with `asyncio`. So, I cannot make this decision. 
I think that more community feedback might help us.

Why do you think that making `Result` awaitable is a good idea? What are the downsides?

**Comment by thedrow** [comment]
First of all, don't tie this library to a specific event loop.
Trio and Curio are also viable options when using async/await.
Second of all, it looks natural:
```python
unwrapped_value = await result
```

This can raise a `TypeError` if the underlying value is not a co-routine or Failure if the co-routine raised an exception.

**Comment by patroza** [comment]
fp-ts approaches this by implementing a [Task monad](https://github.com/gcanti/fp-ts/blob/master/docs/modules/TaskEither.ts.md), perhaps food for thought.
don't know if it makes sense in Python/returns.

**Comment by sobolevn** [comment]
@patroza yes, it totally makes sense! Thanks a lot.

**Comment by sobolevn** [comment]
Help wanted, `asyncio` just does not make any sense for me.
Ping @proofit404 

Plan:
1. Make `returns.functions` work with coroutines 
2. Research where we can use `__await__` with `Result` or `AsyncResult`
3. Forget about it forever as a nightmare! Come to Elixir if you want clear async paradigm

**Comment by proofit404** [comment]
In my opinion, we should implement the first option and postpone awaitable results to the moment in the future when someone will come with a meaningful real-world example of its usage.

To support `pipeline` and `safe` decorators we should 
* Check if a decorated function is a coroutine. With the `inspect` module for example.
* In this case, wrapper function defined by decorator should be a coroutine as well with single `await` in it.

**Comment by sobolevn** [comment]
Partial support is introduced since `0.6.0`
