### ISSUE TITLE
Do we really need `ApplicativeMappable`?

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#604]
Can't we just define that `ApplicativeN` is a subtype of `MappableN`?
Why do we need a separate interface for it?

We don't use it anywhere.

Related https://github.com/dry-python/returns/issues/598

**Comment by thepabloaguilar** [comment]
> Can't we just define that ApplicativeN is a subtype of MappableN?

I think we can make `ApplicativeN` a subtype of `MappableN`!

> Why do we need a separate interface for it?

I think we don't need it!! `Applicative` is a `Functor`

> ... It says that if we want to make a type constructor part of the Applicative typeclass, it has to be in Functor first. That's why if we know that if a type constructor is part of the Applicative typeclass, it's also in Functor, so we can use fmap on it.
##### Extracted from [here](http://learnyouahaskell.com/functors-applicative-functors-and-monoids)
