### ISSUE TITLE
We don't have an interface to represent `Failable` types

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#623]
Currently we treat `ResultLikeN` as a basic failable:

```python
class ResultLikeN(
    ContainerN[_FirstType, _SecondType, _ThirdType],
    bimappable.BiMappableN[_FirstType, _SecondType, _ThirdType],
    rescuable.RescuableN[_FirstType, _SecondType, _ThirdType],
    Lawful['ResultLikeN[_FirstType, _SecondType, _ThirdType]'],
): ...
```

But, that's not correct. And even our own code supports this statement by having `Maybe`:

```python
class MaybeLikeN(
    ContainerN[_FirstType, _SecondType, _ThirdType],
    rescuable.RescuableN[_FirstType, _SecondType, _ThirdType],
    Lawful['MaybeLikeN[_FirstType, _SecondType, _ThirdType]'],
): ...
```

They are almost identical (except for `.alt` part, but more on this later). So, we need a basic interface to represent both of them.

I can see several things here:
- [ ] We need to create a new `interfaces.failable` module, we would define two types there
- [ ] First type would be `Failable` that extends both `ContainerN` and `Rescueable`. This type is supposed to have only a single failed value
- [ ] Second type would be `DiverseFailable` that extends both `Failable` and `BiMappable`. The thing here is that some types can only fail with one value: `None`, `0`, `False`, `NaN`, you name it. But, other types can fail with literally any value: like `Result` does. So, some types just don't need `.alt` and `.from_failure` methods
- [ ] We need to move `swap` and `.from_failure` from `ResultLikeN` to `DiverseFailable` type
- [ ] Type test all the things!
- [ ] Change docs where we already cover this

**Comment by sobolevn** [comment]
@thepabloaguilar will you be able to take this one?

**Comment by thepabloaguilar** [comment]
Yep

**Comment by thepabloaguilar** [comment]
@sobolevn I didn't get the idea here, can you provide some examples?

Using your explanation I thought something like this:
```python
class FailableN(
    ContainerN[_FirstType, _SecondType, _ThirdType],
    rescuable.RescuableN[_FirstType, _SecondType, _ThirdType],
):
    ...

class DiverseFailableN(
    FailableN[_FirstType, _SecondType, _ThirdType],
    BiMappableN[_FirstType, _SecondType, _ThirdType],
):
    ...
```

Where `Maybe` inherit from `Failable` and `Result` from `DiverseFailable`, right??

Because does not make any sense `Maybe` with the `alt` method (from `BiMappableN`), the only possible failure value is `None`! Maybe you've said this, I'm just confirming 😄

**Comment by sobolevn** [comment]
> Where Maybe inherit from Failable and Result from DiverseFailable, right?

Yes!
