### ISSUE TITLE
Add a hypothesis test case with an expected failure

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#630]
We need a test like https://github.com/dry-python/returns/blob/master/tests/test_contrib/test_hypothesis/test_laws/test_custom_type_with_init.py but it should fail.

This way we would check that it is possible to violate the law and your test will fail.
We would also need to check that we have `strict-xfail` setup in `pytest`.

@thepabloaguilar will you take this one, please?

**Comment by thepabloaguilar** [comment]
Sure!

**Comment by thepabloaguilar** [comment]
I've made a test, it failed. How can I push it to check the errors?? Using something like:
```python
with pytest.raises(...):
    check_laws(...)
```

**Comment by sobolevn** [comment]
`xfail` as I have mentioned earlier: https://docs.pytest.org/en/latest/skipping.html

**Comment by thepabloaguilar** [comment]
I'm having some problems to figure out how I can make `symmetry_law` fail!!

```python
@final
class _LawSpec(LawSpecDef):
    @law_definition
    def symmetry_law(
        first: _EqualType,
        second: _EqualType,
    ) -> None:
        """If ``A == B`` then ``B == A``."""
        assert first.equals(second) == second.equals(first)
```

**Comment by sobolevn** [comment]
We can have just any law that fails.

**Comment by thepabloaguilar** [comment]
Nice, I'll remove the `equable.SupportsEquality`
