### ISSUE TITLE
Consider implementing __str__ / __repr__ for suitable containers

### ISSUE THREAD

**Issue by mysticfall** [dry-python/returns#636]
# Bug report

## What's wrong

When writing test cases for a method that returns `Maybe[T]`, I found that pytest reports a failure as follows which is not very readable:
> <returns.maybe._Some object at 0x7fddfe56c140> != <returns.maybe._Some object at 0x7fddfe5aea00>

## How is that should be

It would be much better, if `Some` implemented `__str__` (and maybe also `__repr__`) so that it could look like below:
> <Some(10) != Some(20)>

## System information

- `python` version: 3.8
- `returns` version: 0.14.0

**Comment by sobolevn** [comment]
@mysticfall will you please send a PR for this?

**Comment by mysticfall** [comment]
@sobolevn I'd be willing to try. But for now my hands are tied with my own project, so probably I'll need some time before I could start working on it.

**Comment by thepabloaguilar** [comment]
This seems easy, `Maybe` and all of our container inherit from [BaseContainer](https://github.com/dry-python/returns/blob/baa5a9cb64ac9f63feed4ab99a1b9b84b2b37272/returns/primitives/container.py#L11)

We've `__str__` defined but not `__repr__`, this problem can be solve by switching from `__str__` to `__repr__` because when we don't define str dunder it'll use the representation of the object!
Or we can define both if wished, but we just can make this switch and everything will continue working.

```python
>>> class Example:
...     attr = 42
... 
>>> print(Example())
<__main__.Example object at 0x7f3f1b5d07c0>
>>> class Example:
...     attr = 42
...     def __repr__(self):
...             return f'<Example: {self.attr}>'
... 
>>> print(Example())
<Example: 42>
>>> class Example:
...     attr = 42
...     def __str__(self):
...             return f'<Example: {self.attr}>'
... 
>>> print(Example())
<Example: 42>
```

**Comment by raoashish10** [comment]
@thepabloaguilar I would like to try solving this issue for Hacktoberfest. Where can I contact you for any doubts?

**Comment by sobolevn** [comment]
There would be also some tests to fix, because we tested `repr` somewhere.

**Comment by raoashish10** [comment]
@sobolevn Sure I would look into that as well

**Comment by thepabloaguilar** [comment]
@raoashish10 fell free to join in our community group on Telegram, just hit the button below:

[![Telegram chat](https://img.shields.io/badge/chat-join-blue?logo=telegram)](https://t.me/drypython)

**Comment by raoashish10** [comment]
Joined it!

**Comment by thepabloaguilar** [comment]
@raoashish10 are you working on this issue?

**Comment by raoashish10** [comment]
Yes I am @thepabloaguilar My bad I have been caught up a little in some other work

**Comment by thepabloaguilar** [comment]
Ok, don't worry!
