### ISSUE TITLE
Add method to provide default value to Maybe as another Maybe

### ISSUE THREAD

**Issue by mysticfall** [dry-python/returns#638]
# Bug report

## What's wrong

Currently, we can use `Maybe[T].value_or(default: T)` to evaluate the value of a given `Maybe` container with a fallback value. However, we don't have an easy and compact way to chain `Maybe` containers, so that the first one in the chain which has a value to be chosen as its return value.

## How is that should be

In Scala, there is a method called `orElse` which provides such a feature:
```scala
val value1 = None
val value2 = Some("A")

value1 orElse value2 // Evaluates to Some("A").
value1 orElse value2 getOrElse "A" // Evaluates to "A".
```
It would be nice if we could add an equivalent to `orElse` in Scala, so that we can easily chain multiple `Maybe` containers without having to use conditional statements.

## System information

- `python` version: 3.8
- `returns` version: 0.14.0

**Comment by sobolevn** [comment]
We will have `.rescue` in `Maybe` in `0.15`
Link: https://github.com/dry-python/returns/blob/master/returns/maybe.py#L141

Is it want you need?

**Comment by mysticfall** [comment]
Quite close, as it accepts a callable rather than a value. But probably it's better that way as it can be more flexible and also consistent with existing methods like `or_else_call`.

Please feel free to close this issue. Thanks for the info! :)
