### ISSUE TITLE
`empty` in `Reader` and `Failable` are two different things

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#640]
These two definitions are incompatible. 
We need to rename `Reader.empty` to something else. Like `no_args`.
Or drop it completely, because `...` is easier to write and use.

Related #624 

(I am even surprised it works) 😮

**Comment by thepabloaguilar** [comment]
The explanation of why it's working we can see below:
![image](https://user-images.githubusercontent.com/25423500/95547298-03214f80-09d9-11eb-874e-5644306c66f6.png)

`RequiresContext` doesn't inherit from `SingleFailable` or any type that inherits from `SingleFailable`

**Comment by thepabloaguilar** [comment]
But I agree of changing the name!!

**Comment by sobolevn** [comment]
Any ideas on a better name?

**Comment by thepabloaguilar** [comment]
I liked your idea: `no_args`

**Comment by thepabloaguilar** [comment]
What do you think?
I can work on this one today!

**Comment by sobolevn** [comment]
@thepabloaguilar yes, let's rename it to `no_args`
