### ISSUE TITLE
Test that `Fold` methods are recursion safe

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#644]
Big iterables might potentially trigger `RecursionError` if we would have some wrong abtractions inside.
So, we need to tests that even iterables with big number of elements (bigger than recursion limit) do not raise an error.

We need to test:
- Public methods of `Fold` here https://github.com/dry-python/returns/blob/master/returns/iterables.py
- Recusion limit: https://docs.python.org/3/library/sys.html#sys.getrecursionlimit

Related https://github.com/dry-python/returns/pull/626
Related #598

**Comment by timqsh** [comment]
Hi! I would like to help with this.

**Comment by sobolevn** [comment]
Thanks, @timqsh! Feel free to take this over! 👍
