### ISSUE TITLE
Bad highlight of keyword on documentation

### ISSUE THREAD

**Issue by thepabloaguilar** [dry-python/returns#649]
# Bug report

## What's wrong

When we search something in the `returns` documentation the highlighted term is hard to see on the page. See the example below, this is the `Result` container page and I searched by `result` keyword:

![image](https://user-images.githubusercontent.com/25423500/94645581-91535280-02c2-11eb-8c03-46f637e70be5.png)

URL to reproduce: https://returns.readthedocs.io/en/latest/pages/result.html?highlight=result

## How is that should be

People has to see the highlighted keyword, working example:

![image](https://user-images.githubusercontent.com/25423500/94645736-f8710700-02c2-11eb-8d18-d1cf4b998412.png)

I searched by `logging` keyword!
URL: https://eliot.readthedocs.io/en/stable/generating/actions.html?highlight=logging#logging-functions

**Comment by abhinav72610** [comment]
i want to work on this .. can you assign me

**Comment by sobolevn** [comment]
Thanks a lot, @abhinav72610 !

**Comment by abhinav72610** [comment]
@sobolevn i'm new to this community can you guide me with the directory i nwwd to do the changes

**Comment by sobolevn** [comment]
@abhinav72610 I don't know 🙂 

I have never seen an issue like this. It is somewhere in https://github.com/dry-python/returns/tree/master/docs

**Comment by thepabloaguilar** [comment]
@abhinav72610 here is the theme's [documentation](https://sphinx-typlog-theme.readthedocs.io/en/latest/), maybe can help you!

**Comment by thepabloaguilar** [comment]
@abhinav72610 are you working on this issue?
