### ISSUE TITLE
Missing `methods` module docs

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#655]
Currently we don't have docs for https://github.com/dry-python/returns/tree/master/returns/methods

It should be similar to this page: https://returns.readthedocs.io/en/latest/pages/pointfree.html

**Comment by MichaelAOlson** [comment]
Hey @sobolevn, I would like to work on this. Would you assign it to me?

**Comment by ShubhamNagure** [comment]
Hi,
Any help needed?

**Comment by thepabloaguilar** [comment]
@MichaelAOlson you're assigned!

**Comment by sobolevn** [comment]
@MichaelAOlson friendly ping. Do you need any help from our side? 🙂

**Comment by MichaelAOlson** [comment]
Sorry @sobolevn , life got a little busy. I plan to work on+finish this tomorrow. Thanks for the ping 👍

**Comment by sobolevn** [comment]
No worries ✋ 

Looking forward to reviewing it 🙂
