### ISSUE TITLE
Support python3.9

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#663]
It is just released! We need to add it to our CI and `pyproject.toml` metadata in case everything works correctly. 

This should be done after `0.15` release.

**Comment by sobolevn** [comment]
@thepabloaguilar do you want to work on this? 🙂

**Comment by thepabloaguilar** [comment]
I can do it!!

**Comment by thepabloaguilar** [comment]
Seems `wemake-python-styleguide` has problems with Python 3.9!

https://github.com/dry-python/returns/runs/1236326288?check_suite_focus=true

**Comment by thepabloaguilar** [comment]
Well, I think it's not a problem from WPS!!

While opening an issue on WPS Repo, I added the flag `--bug-report` and the pipeline ran successfully: https://github.com/dry-python/returns/runs/1236352395?check_suite_focus=true

**Comment by sobolevn** [comment]
I have merged`python3.9` support into `wemake-python-styleguide`. But, it is not yet released.

**Comment by thepabloaguilar** [comment]
Do you know when you'll release it?

**Comment by sobolevn** [comment]
In a month!

**Comment by sobolevn** [comment]
Btw, any help is appreciated (especially with existing bugs)

**Comment by thepabloaguilar** [comment]
Issue solved by 017ba7e34a62e60b8251cd27abe9999359d46e9d
