### ISSUE TITLE
Measure and possibly refactor `flow` function

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#706]
Maybe it is better to use `for` loop inside a `flow`'s body? Let's measure.

`flow` is a hot path, so we need to speed this up as much as we can.
Link: https://github.com/dry-python/returns/blob/0f7d02d0c491a7c65c74e6c0645f12fccc53fe18/returns/_internal/pipeline/flow.py

**Comment by Sam-Persoon** [comment]
I did some experimentation with this where I refactored flow to:
```python
def _identity(instance):
    return instance

def _flow_for(
    instance: _InstanceType,
    *functions: _PipelineStepType,
) -> _ReturnType:
    composed = _identity
    for function in functions:
        composed = compose(composed, function)  # type: ignore
    return composed(instance)  # type: ignore
```

I did not encounter any noticeable differences when using tests like:
```python
import timeit

setup='''
from returns.curry import curry
from returns.pipeline import flow, flow_for
from returns.pointfree import bind
from returns.result import Success, Failure

def regular_function(arg):
    return arg

def returns_container(arg):
    return Success(arg)

def returns_failure(arg):
    return Failure(arg)

regular_functions = [regular_function for _ in range(300)]
success_container_functions = [bind(returns_container) for _ in range(300)]
failure_container_functions = [bind(returns_failure) for _ in range(300)]
'''

testcode = '''
flow(1, *regular_functions, lambda x: Success(x), *success_container_functions, *failure_container_functions)
'''

print(timeit.timeit(stmt=testcode, setup=setup, number=100000))

testcode2 = '''
flow_for(1, *regular_functions, lambda x: Success(x), *success_container_functions, *failure_container_functions)
'''
print(timeit.timeit(stmt=testcode2, setup=setup, number=100000))
```

The same holds true for smaller flows like
```
flow(1, regular_function, returns_container, returns_failure)
```
This makes sense as the internals of reduce is almost a copy of my `_flow_for` function with only special handling if no initial value is specified, but this should be negligible as the wrapping in an iterator and getting the first value are also happening in the normal loop. See https://github.com/python/cpython/blob/37440eef7f9a0c27e13fc9ce0850574bb00688b0/Lib/functools.py#L237-L263
