### ISSUE TITLE
HKT subtype method signature "incompatible with supertype"

### ISSUE THREAD

**Issue by joelberkeley** [dry-python/returns#708]
# Bug report

I'm following [your docs](https://sobolevn.me/2020/10/higher-kinded-types-in-python) for HKTs. Thanks for the new feature btw. I'm seeing type errors that I don't understand

```python
from __future__ import annotations
from abc import ABC, abstractmethod
from typing import TypeVar, Generic, Mapping, Iterator, Callable
from returns.primitives.hkt import Kind1, kinded, SupportsKind1

T_co = TypeVar("T_co", covariant=True)
U = TypeVar("U")
V = TypeVar("V")
G = TypeVar("G", bound="Grouping")


class Grouping(ABC, Generic[T_co]):
    @kinded
    @abstractmethod
    def map(self: G, f: Callable[[T_co], U]) -> Kind1[G, U]:
        ...

    @kinded
    @abstractmethod
    def zip_with(self: G, other: Kind1[G, U], f: Callable[[T_co, U], V]) -> Kind1[G, V]:
        ...


class One(Grouping[T_co], SupportsKind1["One", T_co]):
    def __init__(self, o: T_co):
        self._o = o

    def get(self) -> T_co:
        return self._o

    def map(self, f: Callable[[T_co], U]) -> One[U]:
        return One(f(self._o))

    def zip_with(self, other: One[U], f: Callable[[T_co, U], V]) -> One[V]:
        return One(f(self.get(), other.get()))
```
I'm seeing
```
grouping.py:31: error: Signature of "map" incompatible with supertype "Grouping"
grouping.py:34: error: Signature of "zip_with" incompatible with supertype "Grouping"
```
Can you help explain what's wrong? In the docs you use
```python
class Kind(Generic[_InstanceType, _FirstTypeArgType]):
    """Used for HKT emulation."""
```
whereas I use `Kind1`. Am I doing that right?

On a separate but related note, I was also seeing, for map signature on `Grouping`
```python
def map(self: Kind1[G, T_co], f: Callable[[T_co], U]) -> Kind1[G, U]:
```
the error
```
grouping.py:15: error: The erased type of self "returns.primitives.hkt.KindN[G`-1, T_co`1, Any, Any]" is not a supertype of its class "grouping.Grouping[T_co`1]"
```
but it's not entirely clear to me whether I should use `self: G` instead, or make `Grouping` subclass `SupportsKind1["Grouping", T_co]`

## System information

- `python` version: 3.8
- `returns` version: 0.15.0
- `mypy` version: 0.782

**Comment by sobolevn** [comment]
Hi, @joelberkeley! Thanks a lot for trying `returns` out!

There are couple of things I would like to highlight:
1. You abstract definitions should not be `@kinded`, because `mypy` won't allow to override it. That's how it works for now. Because internally all `@kinded` functions are `Kinded[func]` decsriptors. And `mypy` does not allowed to override custom descriptors. I will submit a patch to `mypy` soon

Example: https://github.com/dry-python/returns/blob/d50215daef0e9e7027bd7fe9e8ff16d41d21d5e8/returns/interfaces/mappable.py#L76-L83

2. We cannot help with the error messages like `Signature of "map" incompatible with supertype "Grouping"`, because, again, this happens because of descriptors bug
3. `whereas I use Kind1. Am I doing that right?` Yes, looks like it! Don't forget to apply `@kinded` on `map` function
4. `is not a supertype of its class "grouping.Grouping[T_co]"` should be gone after 1 and 2 are fixed

**Comment by sobolevn** [comment]
> mypy version: 0.782

We only officially support `0.790`, I recommend to update it as well!

**Comment by joelberkeley** [comment]
> You abstract definitions should not be @kinded ...
thanks, that fixes the errors with `map`

> whereas I use Kind1. Am I doing that right? Yes, looks like it! Don't forget to apply `@kinded` on map function
oh ok, why's that? the return type on the implementations aren't `Kind1`, so why is `@kinded` necessary?

I'm now seeing
```
grouping.py:32: error: Argument 1 of "zip_with" is incompatible with supertype "Grouping"; supertype defines the argument type as "KindN[One[T_co], U, Any, Any]"
grouping.py:32: note: This violates the Liskov substitution principle
grouping.py:32: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
```
Replacing the type with `Kind1[One, U]` with or without `@kinded` doesn't fix it

**Comment by sobolevn** [comment]
> oh ok, why's that? the return type on the implementations aren't Kind1, so why is @kinded necessary?

My bad, I am reading this in bed 😆 

> supertype defines the argument type as "KindN[One[T_co], U, Any, Any]"

Here's how to fix it: https://github.com/dry-python/returns/blob/master/returns/io.py#L130

**Comment by joelberkeley** [comment]
ok, thanks. I can then get it to pass using `dekind` within the method.

A bit of feedback: It would be really nice if there was some way of being able to specify `One[U]` in the function arguments rather than `Kind[One, U]`, as it's much more readable and is standard type hint style. I appreciate we can't do this when `One` is replaced by a generic type constructor e.g. `G`, but it would be great if it could be universally possible with concrete container types like `One`
