### ISSUE TITLE
Update `add-path` in github actions

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#721]
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by thepabloaguilar** [comment]
I think we don't need that update:

> Action and workflow authors who are setting environment variables via STDOUT should update any usage of the set-env and add-path workflow commands to use the new environment files.

Here we don't use `set-env` and `add-path`!

**Comment by sobolevn** [comment]
Thanks!
