### ISSUE TITLE
current init breaks `import returns` usecase

### ISSUE THREAD

**Issue by asmodehn** [dry-python/returns#73]
```
(crypy-PletnYfd)alexv@pop-os:~/Projects/crypy$ python3
Python 3.7.2 (default, Jan  8 2019, 16:12:09) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import returns
>>> returns.result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'returns' has no attribute 'result'
>>> returns.__file__
'/home/alexv/.local/share/virtualenvs/crypy-PletnYfd/lib/python3.7/site-packages/returns/__init__.py'
>>> returns.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'returns' has no attribute '__version__'

```

I believe `__init__.py` should contain the modules or not be there at all, for both usecases to work.
The usage given in example ` from returns.result import Result` works because python import finds `result.py` as part of the package, but the module is not loaded as part of the super/parent package.

**Comment by proofit404** [comment]
Hi, thank you for the report!

I know `wemake-services-styleguide` used in the project has rules against it.

@sobolevn what do you think?

Should we export public API to the top-level package?

Regards, Artem.

**Comment by sobolevn** [comment]
Why do you want to use imports like that?

Why can't you use `from returns.results import Result` or `from returns import result`?

**Comment by asmodehn** [comment]
I can get it to work in many different ways. The point here is only for
code clarity purpose.

When I see `result` in my code I want to know where it comes from (without
going back up to the top of the module where all the imports are, which
might not be included in code I copy paste to forums, issues, and
others...).

So I want to write `returns.result` everywhere I use it.
Which means I need to `import returns`.

It just for convenience, but I havent seen any downside to it yet, so I
write code like this whenever I can.

I naively expected it to work for `returns`, so I thought I'd post this
issue.

**Comment by proofit404** [comment]
```python
import returns.result
returns.result.Result()
```
vs
```python
import returns
returns.Result()
```
I would prefer the second one.

**Comment by sobolevn** [comment]
Ok, let's expose public API in `returns` module.

**Comment by sobolevn** [comment]
Closed by https://github.com/dry-python/returns/commit/4e9ab7bd856b9af679a176df7a18b2f40d917dd4
