### ISSUE TITLE
Question: IOResult usage

### ISSUE THREAD

**Issue by enzoschmidlin** [dry-python/returns#738]
Hi!

First of all, this is a great library, very high quality code and documentation. Thank you!

I have been trying to implement it in a personal project - mostly as a learning opportunity. It is some IO-heavy code, with API endpoints and DB usage - not ideal, but a real-world application :) I ran into some questions about `IOResult` and couldn't find the answers, I was wondering if you could help me:

- Is there an alternative to `unsafe_perform_io()` for `IOResult`? `unsafe_perform_io()` itself sort of works, but you seem to have to apply it twice and it doesn't type check - it looks like it was written for `IO` only. Or do I need to convert an `IOResult` to something else?
- Is `IOResult` meant to flow throughout the entire application? As in, once you read something from the DB for instance, you have an `IOResult`. If you process the result in another function, is the output type still `IOResult`? This seems to be the case in the documentation. Or is there a point where you can "break" with the `IOResult` type and make it a `Maybe` - or any other container - based on whether some processing worked or not?

Thank you in advance!

**Comment by sobolevn** [comment]
Hi, @enzoschmidlin! 

Thanks for your kind words!

That's what I think about the listed problems:
1. I usually coerce `IOResult` to `IO[Result]` first, then I can use `unsafe_perform_io`. It might be also helpful to coerce the `IO[Result]` into `IO[Value]` or `IO[Union[]]`
2. Yes, parts that are touched with `IO` should be dealing with `IO` forever. The main idea is that I try to find as many pure logic functions as I can. This way I can write simple code and compose it with `IOResult` via `map` or `alt` 

Btw, feel free to join our little telegram community: https://t.me/drypython

**Comment by enzoschmidlin** [comment]
Thank you for your incredibly fast response @sobolevn! This is very helpful!
