### ISSUE TITLE
Add python 3.8 support

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#74]
It will be released soon.
We need to support it before `1.0.0` release.

**Comment by tewe** [comment]
What got broken by 3.8?

What new feature do you want to support?

**Comment by sobolevn** [comment]
Nothing should be broken. We only need to test it in CI.

**Comment by tewe** [comment]
You mean add 3.8 to the CI? Sorry, I don't want to give Travis full access to my GitHub account.

I was asking because I'm not clear on what would need doing to close this issue.
