### ISSUE TITLE
Question: How to restore after failure in the middle of the flow?

### ISSUE THREAD

**Issue by ChameleonTartu** [dry-python/returns#790]
I am working for some time with railway-oriented programming and think that it is a cool paradigm.

I got a case that I cannot wrap up my head around.

```
return flow(
  collection,
  partial(get_key, path=config.get(PATH)),
  bind(
    partial(
      apply_handler_one, handler_one=config.get(HANDLER_ONE),
    )
  ),
  map_(
    partial(
      apply_handler_two, handler_two=config.get(HANDLER_TWO),
    ),
  ),
)
```

This issue is that sometimes I need to rescue between `apply_handler_one` and `apply_handler_two`.

There are many ways how to do it. One is to store the state before applying `flow`, but maybe there is a better way?

**Comment by sobolevn** [comment]
Hi, @ChameleonTartu!

So, you basically have just two options to act when something fails:
- You can use `alt` to change the failure type
- You can use `rescue` to change any failure to the desired success type

There are some helpers around it, like `bimap`, which either `map`s or `alt`s.

I don't really follow why do you want to store the state, but I guess this is specific to your usecase.

**Comment by ChameleonTartu** [comment]
@sobolevn I was thought about rescuing, but when I rescue from the `Failure` state, I don't have data anymore but only an exception. If I change the function and return the data, I will break SRP (Single Responsibility Principle).

Therefore, there are 2 ways to proceed, store state and restore from this state or change the function's scope and break SRP. Both ways are not good, but what other options do I have?

My general thought was, I don't want to fail but rather log the failure and proceed as if the failure has never happened.

**Comment by sobolevn** [comment]
You can have a custom exception type that can store your data inside or use `Result[SuccessType, FailureType]` where `FailureType` is not an exception (that's completely fine!)

**Comment by thepabloaguilar** [comment]
Closing this issue due inactivity!

@ChameleonTartu fell free to reach us out again or reopening this issue if you didn't find a great solution!
