### ISSUE TITLE
Documentation: possible error in "Collecting an iterable of containers into a single container" example

### ISSUE THREAD

**Issue by lordgordon** [dry-python/returns#816]
Looking at the section ["Collecting an iterable of containers into a single container" in the Container](https://returns.readthedocs.io/en/latest/pages/container.html#collecting-an-iterable-of-containers-into-a-single-container) page of the documentation, the following example is presented:

```
>>> from returns.maybe import Maybe, Some, Nothing, maybe

>>> source = {'a': 1, 'b': 2}
>>> fetched_values: Maybe[int] = [
...     maybe(source.get)(key)
...     for key in ('a', 'b')
... ]
```

The type of `fetched_values` shouldn't be `List[Maybe[int]]`?

**Comment by sobolevn** [comment]
@lordgordon yes, it should! Can you please send a PR with the fix? 

Thanks! 👍
