### ISSUE TITLE
Many types are incorrect

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#85]
After a review done by @astynax it was revealed that many types are incorrect.

We have privately discussed all the problems and solutions.
Here's the short version:
1. We should only deal with `Result` itself, `Success` and `Failure` should return `Result` instances
2. We should not work with `Success` and `Failure` directly, since there's no such thing, only `Result`
3. `Result` functions should always return `Result` changing only the type signature

Btw, @astynax is now a core-dev of `returns` library. Congrats :tada:

**Comment by proofit404** [comment]
@astynax Welcome to the team!
