### ISSUE TITLE
Question regarding mypy return type inference

### ISSUE THREAD

**Issue by martindederer** [dry-python/returns#858]
Hi guys,

i am new to returns and ran into an issue that i can't seem to figure out. I am having difficulty providing a proper type annotation.

For context: I want to build a variety of pipelines that share similar traits but can differ in certain details. My idea was to create factory functions (see "range_guard" function in example) which return a function that is used in composing the pipeline. I omitted the other pipeline steps for clarity.

Unfortunately mypy can not infer the return type of the "range_guard" function and i don't know how to work around this. Maybe you can give me a pointer on how to tackle this?

```
def range_guard(minimum: int, maximum: int) -> ???:
    @bind
    def inner(x: int) -> Result[int, ValueError]:
        if minimum <= x <= maximum:
            return Success(x)

        else:
            return Failure(ValueError('Not in range'))

    return inner
    
    
pipeline = pipe(range_guard(-5, 5))
```

Thank you! :)

**Comment by martindederer** [comment]
Sorry, i could not find the option to add the "need help" and "question" labels. :|

**Comment by martindederer** [comment]
Ok, as customary i think i found the solution shortly after creating this issue. Is this the idiomatic solution to the problem?

```
from returns.curry import curry
from returns.pipeline import pipe
from returns.pointfree import bind
from returns.result import Result, Success, Failure


def float_to_int(x: float) -> Result[int, ValueError]:
    try:
        y = int(x)

        return Success(y)

    except ValueError as e:
        return Failure(e)


@curry
def range_guard(minimum: int, maximum: int, x: int) -> Result[int, ValueError]:
    if minimum <= x <= maximum:
        return Success(x)

    else:
        return Failure(ValueError('Not in range'))


pipeline = pipe(
    float_to_int,
    bind(range_guard(-5, 5))
)

print(pipeline(-5))
print(pipeline(1.9))
```

**Comment by sobolevn** [comment]
Hi, @martindederer!

Your last solution (https://github.com/dry-python/returns/issues/858#issuecomment-796917161) looks valid!
The only thing I would change is making `range_guard` to return a function instead. Because, it is better not to curry things if possible.

Don't forget that we have a friendly chat: https://t.me/drypython
You might get help quicker there! 👍

**Comment by martindederer** [comment]
Thanks for the feedback. :+1: 

Apparently jamming the bind decorator in the `range_guard` factory function was what was causing mypy to act up with the implementation in my [initial comment](https://github.com/dry-python/returns/issues/858#issue-829354783). This is the mypy message that i got back then. Apparently mypy was not able to infer the return type correctly.

```
$ pipenv run mypy .
test.py:33: error: Need type annotation for 'pipeline'
Found 1 error in 1 file (checked 1 source file)
```

Moving the bind call to the arguments of the pipe call solved the issue. :)

```
from returns.pipeline import pipe
from returns.pointfree import bind
from returns.result import Result, Success, Failure, safe


@safe
def float_to_int(x: float) -> int:
    return int(x)


def range_guard(minimum: int, maximum: int):
    def inner(x: int) -> Result[int, ValueError]:
        if minimum <= x <= maximum:
            return Success(x)

        else:
            return Failure(ValueError('Not in range'))

    return inner
    
    
pipeline = pipe(
  float_to_int,
  bind(range_guard(-5, 5))
)

print(pipeline(1.9))
print(pipeline(-5))
print(pipeline(-6))
```

Thanks for pointing me to the chat! I will use it next time.

**Comment by sobolevn** [comment]
Note, that `range_guard` should have a return type defined as `Callable[[int], Result[int, ValueError]`
It is probably a typo, but nevertheless!

Gald that it helped!
