### ISSUE TITLE
returns.assert_trace doesn't work with @safe-wrapped functions

### ISSUE THREAD

**Issue by ftruzzi** [dry-python/returns#862]
First of all, thank you! I really appreciate your work and your help on the Telegram group :)

# Bug report

## What's wrong
`returns.assert_trace` fails to "intercept" containers created from `@safe` decorators.

```python
# works
def func_1(n) -> Result[int, Exception]:
    if n == 0:
        return Failure(Exception())
    return Success(n + 1)

# doesn't work
@safe
def func_1(n) -> int:
    if n == 0:
        raise Exception()
    return n + 1


def test_func_1(returns: ReturnsAsserts):
    with returns.assert_trace(Success, func_1):
        flow(1, func_1)
```

The test with the wrapped function returns

```
FAILED returns_test.py::test_func_1 - Failed: No container Success was created
```

I tried doing this, but no difference:
```python
def test_func_1(returns: ReturnsAsserts):
    with returns.assert_trace(Success, safe(func_1)):
        flow(1, safe(func_1))

```

## How is that should be
The above test should pass

## System information

- `python` version: 3.8.0
- `returns` version: 0.15.0
- `pytest` version (if any): 6.2.2

**Comment by thepabloaguilar** [comment]
Hello @ftruzzi, thank you for open this issue!

I found the problem here, our plugin can search the container in the entire call stack, so, the test below should pass:
```python
def func_one():
    return func_two()

def func_two():
    return Success(42)

def test_something(returns: ReturnsAsserts):
    with returns.assert_trace(Success, func_one):
        func_one()
```

The problem here is when we use `safe`, we don't have `func_one` in the call stack anymore, let me try to explain:
```python
def func_one():
    return Success(42)

# When we found `Success` call while calling `func_one` the call stack is something like:
# - Success (call)
# - func_one (call)
# So we can reach `func_one`

@safe
def func_one():
    return 42

# Using `safe` decorator all of the containers are created inside it
# So, when we find a desired container creation call we have this:
# - Success (call)
# - safe (call)
# Instead of
# - func_one (call)
# - Success (call)
# - func_one (call)
# And that makes sense because we already returned from `func_one`
```

**Comment by ftruzzi** [comment]
Thanks for the explanation!

I have never looked into the Python call stack, but maybe this can help?

https://medium.com/@genexu/extracting-the-wrapped-function-from-a-decorator-on-python-call-stack-2ee2e48cdd8e

**Comment by thepabloaguilar** [comment]
> Thanks for the explanation!
> 
> I have never looked into the Python call stack, but maybe this can help?
> 
> https://medium.com/@genexu/extracting-the-wrapped-function-from-a-decorator-on-python-call-stack-2ee2e48cdd8e

Oh sorry, I've just delete it!! I'll put back again below:

Hello @ftruzzi, thank you for open this issue!

I found the problem here, our plugin can search the container in the entire call stack, so, the test below should pass:
```python
def func_one():
   return func_two()

def func_two():
   return Success(42)

def test_something(returns: ReturnsAsserts):
   with returns.assert_trace(Success, func_one):
       func_one()```
The problem here is when we use `safe`, we don't have `func_one` in the call stack anymore, let me try to explain:
```python
def func_one():
   return Success(42)

# When we found `Success` call while calling `func_one` the call stack is something like:
# - Success (call)
# - func_one (call)
# So we can reach `func_one`

@safe
def func_one():
   return 42

# Using `safe` decorator all of the containers are created inside it
# So, when we find a desired container creation call we have this:
# - Success (call)
# - safe (call)
# Instead of
# - func_one (call)
# - Success (call)
# - func_one (call)
# And that makes sense because we already returned from `func_one````

**Comment by thepabloaguilar** [comment]
@ftruzzi I think the problem here can be other thing, I'm exploring now!

**Comment by thepabloaguilar** [comment]
Btw, fell free to submit a PR when you find a solution!

**Comment by thepabloaguilar** [comment]
Ok, we have a weird problem here! I wrote this test below:
```python
def test_(returns: ReturnsAsserts):
    @safe
    def function():
        return 42

    with returns.assert_trace(Success, function):
        function()
```

When a run the test, it reaches this line here https://github.com/dry-python/returns/blob/master/returns/contrib/pytest/plugin.py#L138
So, our `_trace_function` is working correctly and the test should pass but something is getting wrong because this `except` here (https://github.com/dry-python/returns/blob/master/returns/contrib/pytest/plugin.py#L68) isn't handling the exception. Maybe a most outer `except` is handling it! We need to discovery

**Comment by ftruzzi** [comment]
good catch! I think the `@safe` decorator itself is catching the exception 😄

**Comment by ftruzzi** [comment]
@thepabloaguilar I've opened a PR here https://github.com/dry-python/returns/pull/863, let me know if it looks good to you. Thanks!

**Comment by ftruzzi** [comment]
@sobolevn would you mind releasing a new version on PyPI which includes this fix? I'm trying to publish my library and it fails with

```
Invalid value for requires_dist. Error: Can't have direct dependency: 'returns @ git+https://github.com/dry-python/returns.git@ae928f50'
```

because packages published on PyPI can only depend on other projects published there (https://github.com/pypa/pip/issues/6301)

Thanks!

**Comment by sobolevn** [comment]
@ftruzzi yes, sure!

**Comment by sobolevn** [comment]
@ftruzzi done! Thanks a lot! https://github.com/dry-python/returns/releases/tag/0.16.0

**Comment by sobolevn** [comment]
I am really excited to see your lib! 👍

**Comment by ftruzzi** [comment]
Thanks! Really appreciate your quick reply and help.

> I am really excited to see your lib! 👍

Here it is, I know it can be controversial but hopefully you're not against it 🙃 https://github.com/ftruzzi/libgen_uploader
