### ISSUE TITLE
Override __bool__ function for Maybe and Result

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#95]

**Comment by sobolevn** [comment]
This can cause confusion: some containers will be convertable to `bool` while other is not.
Better to leave `__bool__` as is: always `True`.

**Comment by thedrow** [comment]
I'm reopening this since it's convenient to do the following:
```python
if maybe:
  value = maybe.unwrap()
else:
  pass # handle this case
```

**Comment by sobolevn** [comment]
Also related:
- #301 
- #300

**Comment by homeworkprod** [comment]
This seems like an interesting approach.

It depends a lot on the name of the evaluated variable/callable to make sense to the reader, though, I think.

**Comment by thedrow** [comment]
Naming variables is one of the first things you learn when you program (hopefully)

**Comment by sobolevn** [comment]
Ok, I've made a decision: we should leave `is_successful` function as the main and only to tell whether container was successful or not.

Reasoning:

1. `__bool__` is too implicit. It is hard to tell: is `bool(Success(False))` a `True` or a `False`? Supporting `__bool__` also opens a door of overusing `if container:` conditions.
2. Custom method like `is_success` and `is_failure` requires either duplicating `is_successful` or removing it. I don't see a reason for duplication or a breaking change here.
3. `is_successful` on the other hand limits what can be passed in there on a type level. It is already there and costs only a single import. 

So, it is going to stay as is. Thanks a lot for participating in the discussion and proposing lots of good alternatives!
